const SYMBOL_DESCRIPTIONS = {
  "kn_cat": "Master ruin of the Knowledge category; anchors all Knowledge-class ruins in a composition.",
  "lf_cat": "Master ruin of the Life category; anchors all Life-class ruins in a composition.",
  "lt_cat": "Master ruin of the Light category; anchors all Light-class ruins in a composition.",
  "me_cat": "Master ruin of the Memory category; anchors all Memory-class ruins in a composition.",
  "so_cat": "Master ruin of the Sound category; anchors all Sound-class ruins in a composition.",
  "sp_cat": "Master ruin of the Space category; anchors all Space-class ruins in a composition.",
  "ti_cat": "Master ruin of the Time category; anchors all Time-class ruins in a composition.",
  "kn_sub_div": "Tunes the inscription to read probabilistic signal patterns and surface hidden or future information.",
  "kn_sub_enc": "Binds a specified intent into an object or phrase so it carries persistent operational force.",
  "kn_sub_ill": "Alters the perceptual input of a target without modifying the underlying physical state.",
  "kn_sub_pro": "Opens a passive channel for transmission of future-state data through the inscriber.",
  "kn_sub_rr": "Enables decoding of existing ruins and sigils regardless of origin or age.",
  "kn_sub_tel": "Establishes direct mind-to-mind data transfer without physical medium.",
  "kn_sub_ts": "Forces all inscribed or spoken output within range to conform to verified fact.",
  "kn_sub_fl": "Grants access to sealed, erased, or classified information at elevated risk to the practitioner.",
  "kn_sub_scr": "Permanently encodes data into a physical medium resistant to degradation and unauthorised access.",
  "kn_sub_mm": "Renders the complete structural topology of a target consciousness as a navigable map.",
  "kn_sub_am": "Extends the practitioner's operational command over the rule-set governing all active ruins.",
  "kn_sub_sc": "Enables the design and instantiation of new, previously undefined ruin forms.",
  "kn_sub_loc": "Activates the foundational inscription language that produces direct effects on physical reality.",
  "kn_sub_bw": "Creates metaphysically binding agreements whose terms are enforced by the inscription itself.",
  "kn_sub_rev": "Delivers complete, instantaneous disclosure of a specified hidden truth to the practitioner.",
  "lf_sub_nec": "Operates on the threshold between living and deceased biological states.",
  "lf_sub_rev": "Restores a target organism to a prior living state, effectiveness decreasing with elapsed time.",
  "lf_sub_hea": "Accelerates the body's native repair processes to return it to baseline function.",
  "lf_sub_gro": "Amplifies and directs the natural growth rate of biological or ecological systems.",
  "lf_sub_sha": "Restructures the physical form of a living organism into a specified alternate configuration.",
  "lf_sub_pla": "Introduces a transmissible biological transformation across a target population.",
  "lf_sub_emp": "Establishes bidirectional sharing of sensory and physiological data between two organisms.",
  "lf_sub_fer": "Amplifies the reproductive and generative potential of a target biological system.",
  "lf_sub_bb": "Creates a persistent operational bond between practitioner and a target animal organism.",
  "lf_sub_blm": "Uses blood as a conductive medium for Life-class ruins, increasing potency proportional to volume.",
  "lf_sub_ver": "Interfaces directly with plant-based biological networks including root and fungal systems.",
  "lf_sub_bon": "Enables precise structural modification of skeletal and mineralised tissue in living organisms.",
  "lf_sub_sou": "Operates directly on the non-physical animating component of a living organism.",
  "lf_sub_vd": "Transfers vital force from a source organism to a target at a 1:1 depletion ratio.",
  "lf_sub_ges": "Accelerates or redirects developmental and incubation processes in biological systems.",
  "lt_sub_pyr": "Summons and directs thermal plasma at a specified intensity and trajectory.",
  "lt_sub_sol": "Draws radiant energy directly from stellar sources for use in large-scale workings.",
  "lt_sub_ill": "Produces directed photon output for purposes of exposure, guidance, or purification.",
  "lt_sub_shb": "Converts shadow regions into structurally solid, manipulable physical matter.",
  "lt_sub_sta": "Interfaces with ancient stellar light to produce slow-acting, high-persistence effects.",
  "lt_sub_bli": "Enables perception across non-visible electromagnetic wavelengths.",
  "lt_sub_lw": "Bends, sculpts, and redirects photons into defined structural or communicative configurations.",
  "lt_sub_pri": "Separates the electromagnetic spectrum into component wavelengths for independent application.",
  "lt_sub_glo": "Operates within low-light transitional zones between full illumination and full darkness.",
  "lt_sub_ref": "Redirects light via reflective surfaces for amplification, surveillance, or signalling.",
  "lt_sub_daw": "Channels the specific photonic properties of first-light for renewal and purification operations.",
  "lt_sub_dus": "Channels the specific photonic properties of last-light for completion and transition operations.",
  "lt_sub_chr": "Uses discrete wavelength values as active operational variables with independent effects.",
  "lt_sub_al": "Generates a zone of absolute photon absence distinct from standard shadow.",
  "lt_sub_lan": "Uses a contained sustained-combustion source as a focal medium for Light-class workings.",
  "me_sub_dw": "Enables entry into and navigation of a sleeping organism's dream-state architecture.",
  "me_sub_mr": "Accesses stored experiential data from a target consciousness at a specified depth.",
  "me_sub_me": "Removes specified data blocks from a target's memory without leaving retrievable traces.",
  "me_sub_ps": "Reads the residual event data stored in a physical location or object.",
  "me_sub_pe": "Replays stored memory content at full perceptual fidelity for the practitioner.",
  "me_sub_nw": "Activates target memory data to produce a specified effect on present behaviour.",
  "me_sub_at": "Retrieves event data stored in physical objects through direct contact.",
  "me_sub_tw": "Modifies the structural processing patterns of a target consciousness, not just its stored data.",
  "me_sub_mp": "Constructs a persistent internal memory architecture for high-volume lossless storage.",
  "me_sub_gr": "Processes accumulated loss data using structured Memory-class operations.",
  "me_sub_ac": "Retrieves stored memory data from ancestral or lineage-linked sources.",
  "me_sub_im": "Overwrites or conceals the identity-constituting memory data of a target.",
  "me_sub_sb": "Converts grief-state data into a directional force usable in subsequent workings.",
  "me_sub_el": "Permanently binds a specified memory to a physical anchor, preventing degradation.",
  "me_sub_fo": "Releases specified memory data from active storage without forcible extraction.",
  "so_sub_son": "Emits directional sound pulses and reads reflections to map physical space.",
  "so_sub_sir": "Outputs specific frequencies that bypass cognitive processing and act directly on instinct.",
  "so_sub_ec": "Constructs real-time spatial models from reflected acoustic data.",
  "so_sub_vs": "Modifies the frequency, timbre, and resonance properties of a voice source.",
  "so_sub_tc": "Generates a concentrated concussive pressure wave as a directed physical force.",
  "so_sub_sw": "Creates a defined zone in which no acoustic signal can propagate.",
  "so_sub_rs": "Identifies and amplifies the resonant frequency of a target structure until failure.",
  "so_sub_wh": "Delivers a sound signal to a single specified recipient with zero ambient propagation.",
  "so_sub_ca": "Generates high-density overlapping frequencies to produce disorienting acoustic interference.",
  "so_sub_sh": "Transmits low-frequency mechanical vibration through ground substrate rather than air.",
  "so_sub_lu": "Outputs biologically-targeted frequencies to induce specified neurological states.",
  "so_sub_bc": "Broadcasts frequencies that increase coordination and response capacity in recipients.",
  "so_sub_hh": "Applies resonant frequencies to biological tissue to accelerate cellular repair.",
  "so_sub_snw": "Erects a standing acoustic barrier that blocks movement and signal propagation.",
  "so_sub_mw": "Delivers audio data directly to a target's auditory processing system without physical vibration.",
  "sp_sub_tel": "Relocates matter instantaneously between two spatially separated coordinates.",
  "sp_sub_pr": "Creates a self-contained stable spatial volume existing outside standard geometry.",
  "sp_sub_gs": "Modifies the direction and magnitude of gravitational force within a defined area.",
  "sp_sub_st": "Forces a localised rupture in the spatial fabric, creating an unstable traversable gap.",
  "sp_sub_pw": "Enables transit through solid matter by temporarily occupying inter-layer spatial gaps.",
  "sp_sub_com": "Reduces effective distance between two fixed points without physical displacement.",
  "sp_sub_exp": "Increases the functional interior volume of a defined space beyond its physical dimensions.",
  "sp_sub_vs": "Routes movement through the spatial voids between objects rather than through matter.",
  "sp_sub_ap": "Fixes a spatial coordinate against movement, entry, or external spatial manipulation.",
  "sp_sub_bw": "Defines and enforces a spatial perimeter that blocks unauthorised traversal.",
  "sp_sub_dl": "Suppresses all spatial-class ruin activity within a defined zone.",
  "sp_sub_map": "Maintains a continuously updated positional record of all objects within a defined area.",
  "sp_sub_lab": "Distorts local spatial geometry to render navigation impossible without the key.",
  "sp_sub_wow": "Manipulates mass and gravitational force at large spatial or planetary scales.",
  "sp_sub_fp": "Reduces effective path length between two points by bending intervening geometry.",
  "sp_sub_tri": "Designates a conditional activation point that fires a specified ruin when a defined spatial condition is met.",
  "ti_sub_ts": "Suspends time progression within a defined local area while the practitioner continues.",
  "ti_sub_cs": "Moves the practitioner or a target forward or backward along the temporal axis.",
  "ti_sub_ag": "Accelerates the aging process of a target at a practitioner-specified rate.",
  "ti_sub_rej": "Reverses the aging process of a target to a specified prior state.",
  "ti_sub_te": "Generates a non-interactive visual replay of recent events at the inscription point.",
  "ti_sub_for": "Reads the probability distribution of near-future states from the current timeline.",
  "ti_sub_hin": "Retrieves and renders past events at full fidelity from any perspective present at the time.",
  "ti_sub_par": "Introduces a deliberate causal contradiction into the timeline as a terminal-force operation.",
  "ti_sub_eon": "Extends temporal perception across geological or civilisational time scales.",
  "ti_sub_dm": "Controls the rate of structural decay and deterioration in a specified target.",
  "ti_sub_lw": "Establishes a repeating time cycle within a defined area on a fixed interval.",
  "ti_sub_ml": "Extracts a single moment from the temporal flow and preserves it in permanent stasis.",
  "ti_sub_acc": "Increases the rate at which time passes within a defined area or for a specified target.",
  "ti_sub_dec": "Decreases the rate at which time passes within a defined area or for a specified target.",
  "ti_sub_er": "Ensures a terminated cycle, system, or state will re-initialise at its designated interval.",
  "kn_01": "Encodes data in a form readable only by the intended recipient.",
  "kn_02": "Seals a knowledge container against access without the correct countersigil.",
  "kn_03": "Locks content behind a logic puzzle solvable only with specified prior knowledge.",
  "kn_04": "Extends perceptual range to include objects and events just outside direct line of sight.",
  "kn_05": "Stores meaning at multiple depth layers readable at different levels of practitioner skill.",
  "kn_06": "Marks a practitioner or inscription as belonging to a specified knowledge lineage.",
  "kn_07": "Seals and labels dangerous knowledge, functioning as both containment and warning.",
  "kn_08": "Generates a cross-referenced index of all related inscriptions within a defined working.",
  "kn_09": "Embeds a secondary message within a primary inscription invisible to unintended readers.",
  "kn_10": "Produces an organised catalogue of all inscriptions within a defined space.",
  "kn_11": "Verifies truth at the moment of inscription; breaks if applied to a false statement.",
  "kn_12": "Unlocks sealed knowledge when presented with the correct operational intent.",
  "kn_13": "Maintains a self-organising expanding record of accumulated knowledge.",
  "kn_14": "Increases perceptual resolution to detect fine detail invisible to unaided observation.",
  "kn_15": "Cancels an existing encryption without exposing the hidden content.",
  "kn_16": "Embeds a readable warning at a location or object detectable by perception-class ruins.",
  "kn_17": "Anchors a working to verified factual data, blocking distortion or false input.",
  "kn_18": "Remains active as an open query, drawing relevant data toward the inscriber until answered.",
  "kn_19": "Inscribes knowledge into ancient or sacred objects, integrating it with the object's identity.",
  "kn_20": "Marks the practitioner's credentials, granting recognition by others in the knowledge tradition.",
  "kn_21": "Prevents unauthorised reading, copying, or destruction of protected inscriptions.",
  "kn_22": "Creates an active inscription that is physically invisible but fully operational.",
  "lf_01": "Promotes growth and development in the biological target it is inscribed upon or near.",
  "lf_02": "Uses the inscriber's blood as a conductive medium, binding vital force to the working.",
  "lf_03": "Maintains functional respiration in environments where atmospheric conditions are insufficient.",
  "lf_04": "Marks and synchronises the natural cycle of a specified biological or ecological system.",
  "lf_05": "Binds a living organism to a location, resisting all relocation attempts.",
  "lf_06": "Creates a dormant Life-class ruin that activates upon detection of specified environmental conditions.",
  "lf_07": "Represents iterative biological unfolding; used to direct staged growth processes.",
  "lf_08": "Permanently increases the growth rate of the biological target it marks.",
  "lf_09": "Synchronises the physiological rhythms of two or more target organisms.",
  "lf_10": "Shields the bearer's vital force from external Life-class manipulation.",
  "lf_11": "Binds two vital-force systems so changes to one propagate to the other.",
  "lf_12": "Marks a defined biological group and enables vital-force sharing across all bonded members.",
  "lf_13": "Sustains long-duration biological processes in continuous self-renewing operation.",
  "lf_14": "Increases the biological repair rate of the target organism above its baseline.",
  "lf_15": "Establishes an optimised protected environment for gestation and early-stage development.",
  "lf_16": "Marks the initiation point of a biological, ecological, or constructed system.",
  "lf_17": "Amplifies the vital-force signal of a target, increasing its detectability to Life-class sensors.",
  "lf_18": "Raises the rate of all biological processes within a defined area for a limited duration.",
  "lf_19": "Returns a biological system to a prior healthy baseline, reversing recent damage.",
  "lf_20": "Draws on the target organism's internal biological reserves to power a secondary working.",
  "lf_21": "Establishes a physical deterrence perimeter using natural biological defence principles.",
  "lf_22": "Links multiple Life-class ruins into a unified operational system.",
  "lt_01": "Generates a sustained long-range luminous output for signalling or location marking.",
  "lt_02": "Projects a targeted directional beam toward a specified recipient or coordinate.",
  "lt_03": "Amplifies existing photon output to maximum functional intensity within a defined zone.",
  "lt_04": "Surrounds the target with a persistent luminous boundary marker.",
  "lt_05": "Stores a photonic purification pulse for release at a specified trigger or time.",
  "lt_06": "Blocks all photon propagation within a defined area, producing total darkness.",
  "lt_07": "Produces a single high-intensity photon burst on activation; single-use.",
  "lt_08": "Enables the practitioner's visual system to penetrate objects, darkness, and active illusions.",
  "lt_09": "Creates a persistent photon emission around the target that resists mundane suppression.",
  "lt_10": "Ignites the target at a specified intensity and duration defined at inscription.",
  "lt_11": "Projects a detection beam that reveals concealed objects, ruins, and identities.",
  "lt_12": "Maintains a small controlled flame at a fixed point without requiring a fuel source.",
  "lt_13": "Stores photon energy in a surface for commanded release at a later time.",
  "lt_14": "Bends light around a defined zone to render it visually consistent with surrounding darkness.",
  "lt_15": "Expands an illuminated boundary outward from a centre point, displacing shadow.",
  "lt_16": "Records the optical state of a moment for later retrieval and replay.",
  "lt_17": "Maintains a photon loop orbiting a fixed point, creating a visible marker and energy boundary.",
  "lt_18": "Establishes a long-duration stellar energy tap; slow activation, high output.",
  "lt_19": "Baseline Light-class anchor ruin used to stabilise and ground larger solar workings.",
  "lt_20": "Accumulates direct solar irradiance for instantaneous high-yield discharge.",
  "lt_21": "Activates during solar transition periods; inert at solar maximum and minimum.",
  "lt_22": "Reaches maximum operational capacity at solar zenith; timing determines output.",
  "me_01": "Preserves a memory in fixed stasis, blocking decay, distortion, or external alteration.",
  "me_02": "Links two memory records so retrieval of one automatically surfaces the other.",
  "me_03": "Generates a continuous automatic record of all events occurring in a defined space.",
  "me_04": "Marks the boundary between waking and dream states as a navigational anchor.",
  "me_05": "Projects a specified memory as a perceptually accessible replay for nearby observers.",
  "me_06": "Causes a target memory to dissolve at a defined rate without triggering awareness of loss.",
  "me_07": "Records and retains event data from a location in an automatically accessible form.",
  "me_08": "Marks the structural gap left by an erased memory without restoring the content.",
  "me_09": "Reads and stores the affective imprint of a space or object without capturing specific events.",
  "me_10": "Organises personal memory storage chronologically with practitioner-defined retrieval access.",
  "me_11": "Blocks all external read, write, and erase operations on a specified memory.",
  "me_12": "Marks a partially degraded memory for recovery processing.",
  "me_13": "Returns a specified memory to its originator for third-person re-experience.",
  "me_14": "Attaches a high-priority retrieval flag to a specified memory, surfacing it under stress.",
  "me_15": "Stores a memory payload for automatic release when a specified future event is detected.",
  "me_16": "Opens a time-limited read window into the recent event history of a specified location.",
  "me_17": "Embeds the practitioner's identity signature into their inscriptions for attribution and tracking.",
  "me_18": "Consolidates residual traces of erased or degraded memories into a partial reconstruction.",
  "me_19": "Records the complete memory state of a target individual at the moment of inscription.",
  "me_20": "Tracks the propagation path of a specified piece of information through successive minds.",
  "me_21": "Stores a representation of a no-longer-existing entity or structure in permanent accessible form.",
  "me_22": "Binds a memory to a specific point in time, preventing retrospective alteration.",
  "so_01": "Produces a specified tone at a defined trigger point for long-range signalling.",
  "so_02": "Delivers an audio signal to a specified recipient independent of physical distance.",
  "so_03": "Generates a sustained harmonic output that aligns the affective states of nearby recipients.",
  "so_04": "Produces interference frequencies that degrade other active sound-class ruins in the area.",
  "so_05": "Creates a persistent acoustic replay of the most recent sounds detected at the inscription point.",
  "so_06": "Locks a space or object to a specified resonant frequency for use in subsequent workings.",
  "so_07": "Outputs a low-frequency deterrent signal that produces unease in nearby subjects.",
  "so_08": "Permanently calibrates a target to a specified resonant frequency.",
  "so_09": "Generates a subsonic pressure output that propagates through solid barriers.",
  "so_10": "Triggers a specified alarm tone when a defined threshold condition is met.",
  "so_11": "Produces a focused high-intensity acoustic output that disorients targets at close range.",
  "so_12": "Emits a sustained low-amplitude frequency that gradually modifies the affective state of nearby subjects.",
  "so_13": "Suppresses output from a single specified sound source without affecting surroundings.",
  "so_14": "Stores a specified acoustic event for later controlled release.",
  "so_15": "Amplifies the harmonic overtones of sounds produced within the inscribed space.",
  "so_16": "Emits acoustic pulses at a specified interval for timing or coordination operations.",
  "so_17": "Transmits mechanical vibration through ground contact rather than through air.",
  "so_18": "Identifies and records the resonant frequency of a target for use in subsequent workings.",
  "so_19": "Establishes a permanent zone of total acoustic absorption at the inscription point.",
  "so_20": "Stores high-yield acoustic energy for single instantaneous explosive discharge.",
  "so_21": "Embeds a subliminal frequency beneath primary audio to prime a specified affective state.",
  "so_22": "Converts any energy input at the inscription point into sustained mechanical vibration.",
  "sp_01": "Designates a spatial sink that draws objects within its radius toward the centre.",
  "sp_02": "Defines an absolute spatial boundary that specified matter or force cannot cross.",
  "sp_03": "Establishes a stable directional spatial tunnel between two defined coordinates.",
  "sp_04": "Increases the functional depth of a defined space below its physical dimensions.",
  "sp_05": "Expands the interior volume of a defined space while leaving its exterior unchanged.",
  "sp_06": "Reduces effective distance between two fixed spatial coordinates.",
  "sp_07": "Creates a spatial discontinuity that blocks passage of specified matter or force.",
  "sp_08": "Excavates a contained spatial pocket inside solid matter without structural disruption.",
  "sp_09": "Measures and records the exact spatial distance between two defined points.",
  "sp_10": "Establishes a stable convergence node for multiple concurrent spatial workings.",
  "sp_11": "Mirrors spatial events at one location to a second paired location.",
  "sp_12": "Marks a spatial transition point between two defined spatial states.",
  "sp_13": "Establishes a reference axis used to orient and anchor large-scale spatial workings.",
  "sp_14": "Creates a central distribution hub from which multiple spatial connections radiate.",
  "sp_15": "Causes the target to travel a defined orbital path around a fixed spatial point.",
  "sp_16": "One element of a paired ruin set that creates a traversable opening between two locations.",
  "sp_17": "Divides a defined space into discrete sections with independently specified properties.",
  "sp_18": "Forces a controlled spatial rupture at the inscription point requiring continuous maintenance.",
  "sp_19": "Records and preserves a specific spatial distance value for reference in future workings.",
  "sp_20": "Applies defined spatial conditions to any object or entity that crosses the marked boundary.",
  "sp_21": "Creates a zone of absolute spatial emptiness impermeable to matter, force, and signal.",
  "sp_22": "Distorts local spatial geometry so that straight-line paths curve around the inscription point.",
  "ti_01": "Accelerates the aging rate of a target at the rate specified at inscription; permanent.",
  "ti_02": "Creates a localised time suspension of minimal duration, sufficient for a single action.",
  "ti_03": "Records all events at the inscription point in a time-ordered log.",
  "ti_04": "Accelerates material deterioration in a specified target at a defined rate.",
  "ti_05": "Designates a moment in time as a retrievable reference point for future temporal workings.",
  "ti_06": "Maintains natural time progression within a defined area, counteracting external temporal alteration.",
  "ti_07": "Reduces the time flow rate within a defined area to a practitioner-specified fraction.",
  "ti_08": "Doubles the time flow rate within a defined local area.",
  "ti_09": "Triggers a specified effect when a defined time interval has elapsed.",
  "ti_10": "Baseline Time-class anchor used to link and coordinate multiple temporal workings.",
  "ti_11": "Synchronises the biological aging and fatigue rates of two specified practitioners.",
  "ti_12": "Establishes a repeating time loop within a defined area; active until the ruin is broken.",
  "ti_13": "Extracts a single moment from the time flow and preserves it in unalterable stasis.",
  "ti_14": "Locks a working to the present moment, blocking interference from past or future alterations.",
  "ti_15": "Functions identically to standard ruins but uses archaic inscription form for greater permanence.",
  "ti_16": "Suspends all time-dependent processes within a defined area without fully arresting them.",
  "ti_17": "Reduces subjective time perception for targets in range without altering objective rate.",
  "ti_18": "Reverts a defined area or object to its recorded state at a specified prior time.",
  "ti_19": "Reduces the operational rate of time-dependent processes in a target to a defined fraction.",
  "ti_20": "Marks and synchronises a cyclic time-based process for use in repeating workings.",
  "ti_21": "Prevents a specified process or state from reaching its natural termination point.",
  "ti_22": "Aggregates residual temporal echo data at a location into a consolidated readable record.",
  "tr_01": "Moves the selected ruin upward on the board.",
  "tr_02": "Moves the selected ruin downward on the board.",
  "tr_03": "Moves the selected ruin left on the board.",
  "tr_04": "Moves the selected ruin right on the board.",
  "tr_05": "Rotates the selected ruin clockwise by one step.",
  "tr_06": "Rotates the selected ruin counter-clockwise by one step.",
  "tr_07": "Increases the size of the selected ruin.",
  "tr_08": "Decreases the size of the selected ruin.",
  "tr_09": "Mirrors the selected ruin left to right.",
  "tr_10": "Mirrors the selected ruin top to bottom.",
  "tr_11": "Reflects the selected ruin across the vertical axis.",
  "tr_12": "Reflects the selected ruin across the horizontal axis.",
  "tr_13": "Scales the selected ruin to a larger size.",
  "tr_14": "Scales the selected ruin to a smaller size.",
  "tr_15": "Moves the selected ruin to the centre of the board.",
  "tr_16": "Places the selected ruin in a circular path around a central point.",
  "tr_17": "Fixes the selected ruin in place against accidental movement.",
  "tr_18": "Connects two ruins so they move together.",
  "tr_19": "Separates previously linked ruins.",
  "tr_20": "Removes all positional constraints from the selected ruin.",
  "tr_21": "Binds the selected ruin to a fixed coordinate on the board.",
  "tr_22": "Creates an identical copy of the selected ruin.",
  "tr_23": "Removes the selected ruin from the board.",
  "tr_24": "Combines two overlapping ruins into a single element.",
  "tr_25": "Separates a merged ruin back into its component parts.",
  "tr_26": "Returns the selected ruin to its default size, rotation, and position.",
  "tr_27": "A direct linear channel connecting two points on the board.",
};
