const SYMBOL_DESCRIPTIONS = {
  "kn_cat": "The Knowledge source ruin. Must anchor all Knowledge-type workings.",
  "lf_cat": "The Life source ruin. Must anchor all Life-type workings.",
  "lt_cat": "The Light source ruin. Must anchor all Light-type workings.",
  "me_cat": "The Memory source ruin. Must anchor all Memory-type workings.",
  "so_cat": "The Sound source ruin. Must anchor all Sound-type workings.",
  "sp_cat": "The Space source ruin. Must anchor all Space-type workings.",
  "ti_cat": "The Time source ruin. Must anchor all Time-type workings.",

  "kn_sub_comprehension": "Manipulates understanding. Forward: grant comprehension of a system, symbol, or idea. Inverted: cause confusion or block understanding.",
  "kn_sub_revelation":    "Manipulates what is hidden. Forward: expose hidden facts or secrets. Inverted: conceal or obscure information.",
  "kn_sub_logic":         "Manipulates reasoning. Forward: sharpen problem-solving and rational thought. Inverted: produce irrational thinking or faulty conclusions.",
  "kn_sub_language":      "Manipulates meaning in words. Forward: translate, understand, or shape language. Inverted: scramble speech or strip meaning from words.",
  "kn_sub_discernment":   "Manipulates the ability to distinguish truth. Forward: see through lies and deception. Inverted: make falsehood appear credible.",
  "kn_sub_skill":         "Manipulates learned ability. Forward: temporarily impart a technique or skill. Inverted: block or suppress a known ability.",
  "kn_sub_pattern":       "Manipulates perceived structure. Forward: reveal connections and underlying order. Inverted: make order appear random or chaotic.",

  "lf_sub_restoration":   "Manipulates the repair of living matter. Forward: heal wounds or reverse biological damage. Inverted: cause decay, sickness, or breakdown.",
  "lf_sub_growth":        "Manipulates biological development rate. Forward: accelerate growth in organisms or tissue. Inverted: stunt, shrink, or wither living things.",
  "lf_sub_vitality":      "Manipulates life energy. Forward: increase strength, stamina, or endurance. Inverted: drain energy and weaken a target.",
  "lf_sub_form":          "Manipulates physical biological structure. Forward: reshape flesh, bone, or plant matter. Inverted: deform or destabilise a body.",
  "lf_sub_instinct":      "Manipulates base biological drives. Forward: heighten senses, reflexes, or animal behaviour. Inverted: suppress instinct or dull perception.",
  "lf_sub_adaptation":    "Manipulates biological resilience. Forward: help a living thing survive harsh conditions. Inverted: make a living thing vulnerable to its environment.",
  "lf_sub_bonding":       "Manipulates connections between living beings. Forward: link organisms through shared life force. Inverted: sever bonds or isolate a life force.",

  "lt_sub_illumination":  "Manipulates the presence of light. Forward: create or intensify light. Inverted: dim light or generate darkness.",
  "lt_sub_visibility":    "Manipulates what can be seen. Forward: make something clearly visible. Inverted: conceal, cloak, or render invisible.",
  "lt_sub_color":         "Manipulates the appearance of colour and aura. Forward: alter or intensify colour. Inverted: drain colour or dull appearance.",
  "lt_sub_reflection":    "Manipulates how light bounces. Forward: create mirrors or reflected images. Inverted: absorb light and eliminate reflections.",
  "lt_sub_refraction":    "Manipulates how light bends. Forward: distort visual space or create illusions. Inverted: correct distortion and reveal illusions.",
  "lt_sub_radiance":      "Manipulates emitted energy. Forward: release intense light or heat. Inverted: smother glow or suppress radiant output.",
  "lt_sub_focus":         "Manipulates the concentration of light. Forward: concentrate light into a precise beam. Inverted: scatter light and blur vision.",

  "me_sub_recall":           "Manipulates access to stored memory. Forward: surface memories clearly. Inverted: block or erase access to memories.",
  "me_sub_retention":        "Manipulates memory persistence. Forward: preserve memories against fading. Inverted: cause memories to decay over time.",
  "me_sub_imprint":          "Manipulates what is recorded in minds, objects, or places. Forward: store a memory or experience. Inverted: remove an imprint.",
  "me_sub_association":      "Manipulates links between memories. Forward: connect one memory to another. Inverted: break the associations between memories.",
  "me_sub_reconstruction":   "Manipulates damaged or incomplete memories. Forward: repair fragmented memories. Inverted: distort or fracture intact memories.",
  "me_sub_emotion":          "Manipulates the emotional content of memory. Forward: strengthen the feeling tied to a memory. Inverted: detach or numb emotional response.",
  "me_sub_identity":         "Manipulates sense of self. Forward: reinforce a stable identity. Inverted: confuse or destabilise self-perception.",

  "so_sub_vibration":  "Manipulates mechanical vibration. Forward: generate tremors or shake objects. Inverted: still vibration and stop motion.",
  "so_sub_volume":     "Manipulates sound intensity. Forward: amplify a sound. Inverted: mute or silence sound entirely.",
  "so_sub_pitch":      "Manipulates sound frequency. Forward: raise, lower, or tune a sound. Inverted: distort or flatten pitch.",
  "so_sub_resonance":  "Manipulates how sound interacts with matter. Forward: make sound pass through or affect physical structures. Inverted: dampen and block resonance.",
  "so_sub_voice":      "Manipulates spoken output. Forward: project, mimic, or empower a voice. Inverted: suppress, steal, or warp a voice.",
  "so_sub_rhythm":     "Manipulates beat and timing of sound. Forward: establish or control a rhythm. Inverted: disrupt rhythm and cause disorientation.",
  "so_sub_hearing":    "Manipulates auditory perception. Forward: enhance hearing or locate sounds. Inverted: deafen or produce false auditory input.",

  "sp_sub_distance":   "Manipulates the effective distance between two points. Forward: shorten distance. Inverted: expand distance.",
  "sp_sub_position":   "Manipulates location. Forward: move an object or person through space. Inverted: lock something in place.",
  "sp_sub_boundary":   "Manipulates spatial barriers. Forward: create a sealed border or barrier. Inverted: dissolve barriers and open sealed spaces.",
  "sp_sub_volume":     "Manipulates the interior space of a container. Forward: expand interior volume beyond physical limits. Inverted: compress or collapse interior space.",
  "sp_sub_direction":  "Manipulates orientation and path. Forward: control the direction of movement or force. Inverted: disorient or reverse direction.",
  "sp_sub_anchoring":  "Manipulates spatial fixity. Forward: fix something to a location absolutely. Inverted: release something from positional constraint.",
  "sp_sub_connection": "Manipulates spatial links. Forward: connect two locations through a traversable path. Inverted: sever spatial connections and isolate locations.",

  "ti_sub_flow":       "Manipulates the rate of time. Forward: accelerate or decelerate time. Inverted: return time to its natural rate.",
  "ti_sub_duration":   "Manipulates how long a moment lasts. Forward: extend a moment. Inverted: shorten a moment.",
  "ti_sub_age":        "Manipulates the aging state of a target. Forward: advance age forward. Inverted: revert age backward.",
  "ti_sub_sequence":   "Manipulates the order of events. Forward: control or fix the sequence of events. Inverted: scramble or reverse sequence.",
  "ti_sub_stasis":     "Manipulates temporal suspension. Forward: freeze something outside the flow of time. Inverted: release something from stasis.",
  "ti_sub_cycle":      "Manipulates repetition of events. Forward: cause events to repeat in a loop. Inverted: break a loop and stop repetition.",
  "ti_sub_timing":     "Manipulates when something occurs. Forward: cause something to happen at a precise moment. Inverted: delay, interrupt, or mistimed an event.",

  "tr_channel":        "Connects two ruins so their effects flow into each other.",
  "tr_curved_channel": "A gently curved channel; connects two ruins along a slight arc.",
  "tr_branch":         "Splits a ruin's output into two parallel paths.",
  "tr_curved_branch":  "A curved branch; splits output into two gently arcing paths.",
  "tr_junction":       "Connects three or more ruins at a single convergence point.",
  "tr_amplify":        "Increases the magnitude of the preceding ruin's output.",
  "tr_diminish":       "Reduces the magnitude of the preceding ruin's output.",
  "tr_invert":         "Reverses the effect of the connected ruin from forward to inverted.",
  "tr_contain":        "Limits the effect of connected ruins to a defined boundary.",
  "tr_extend":         "Extends a ruin's effect outward — marked with an X to denote terminus.",
};
