/**
 * RUINS WRITER — Symbol Descriptions
 * Each entry keyed by symbol id
 */
const SYMBOL_DESCRIPTIONS = {

  /* ══════════════════════════════════════════════════
     CATEGORY SIGILS
  ══════════════════════════════════════════════════ */
  "kn_cat": "The master sigil of Knowledge. Represents all understanding, perception, and the unseen structure of reality. Inscribed to mark a composition as rooted in the pursuit of truth.",
  "lf_cat": "The master sigil of Life. Represents vitality, growth, transformation, and the unbroken cycle of living things. Inscribed to mark a composition concerned with living force.",
  "lt_cat": "The master sigil of Light. Represents illumination, fire, radiance, and energy across the spectrum. Inscribed to mark a composition drawing on photonic or thermal force.",
  "me_cat": "The master sigil of Memory. Represents the persistence of the past, identity, and the impressions that time leaves in matter and mind. Inscribed to mark a composition rooted in what has been.",
  "so_cat": "The master sigil of Sound. Represents vibration, resonance, frequency, and the transmission of meaning through wave. Inscribed to mark a composition that works through acoustic force.",
  "sp_cat": "The master sigil of Space. Represents dimension, distance, boundary, and the geometry of existence. Inscribed to mark a composition that manipulates where and how far.",
  "ti_cat": "The master sigil of Time. Represents sequence, duration, change, and the flow between past and future. Inscribed with great caution — Time ruins compound one another unpredictably.",

  /* ══════════════════════════════════════════════════
     KNOWLEDGE SUBCATEGORIES
  ══════════════════════════════════════════════════ */
  "kn_sub_div": "Divination — Reading signs, omens, and patterns to glimpse future or distant events. The ruin opens a window into what is not yet visible to the unaided eye.",
  "kn_sub_enc": "Enchantment — Embedding intent or meaning into objects and words so they carry power beyond their physical form. The object becomes an extension of the scribe's will.",
  "kn_sub_ill": "Illusion — Shaping perception rather than reality. What the mind believes becomes functionally true for as long as the ruin holds.",
  "kn_sub_pro": "Prophecy — Receiving or transmitting visions of what must come. More passive than Divination — the future speaks through the practitioner rather than being sought.",
  "kn_sub_rr":  "Rune Reading — Interpreting existing ruins and sigils left by others, living or dead. A skilled reader can date, attribute, and decode inscriptions that appear meaningless to others.",
  "kn_sub_tel": "Telepathy — Direct mind-to-mind transmission of thought and feeling without spoken language. Clarity depends on the emotional state of both parties.",
  "kn_sub_ts":  "Truthspeaking — Words spoken or written under this discipline cannot be false. Also used to compel honest answers from those who would deceive.",
  "kn_sub_fl":  "Forbidden Lore — Knowledge that was sealed, erased, or never meant to be known. Dangerous to access; leaves a mark on the practitioner that other ruins can detect.",
  "kn_sub_scr": "Scribing — The art of permanently fixing knowledge into physical form so it endures beyond memory, beyond the death of its author, beyond the fall of civilisations.",
  "kn_sub_mm":  "Mind Mapping — Charting the full structure of a consciousness. Used for navigation, healing, or infiltration of another's mental landscape.",
  "kn_sub_am":  "Arcane Mastery — Deep command of magical theory itself. Understanding the rules that govern all other ruins — their limits, their interactions, their failure modes.",
  "kn_sub_sc":  "Sigil Craft — Designing and creating new ruins from scratch. The engineering discipline of the magic system. Rare, slow, and irreversible once a new ruin is released into the world.",
  "kn_sub_loc": "Language of Creation — The original tongue in which reality was first named. Speaking or writing it has direct effect on the physical world. Only fragments are known.",
  "kn_sub_bw":  "Binding Words — Contracts, oaths, and declarations that carry genuine metaphysical weight. Breaking them has consequences that the ruin itself enforces.",
  "kn_sub_rev": "Revelation — Sudden, complete, overwhelming understanding of a truth. Cannot be sought directly — only invited through patience and preparation.",

  /* ══════════════════════════════════════════════════
     LIFE SUBCATEGORIES
  ══════════════════════════════════════════════════ */
  "lf_sub_nec": "Necromancy — Manipulation of the boundary between life and death. Not inherently malevolent — it is surgery performed on the soul rather than the body.",
  "lf_sub_rev": "Revival — Returning something to a prior living state. Healing taken to its extreme limit. Effectiveness diminishes with time elapsed since death.",
  "lf_sub_hea": "Healing — Restoration of the body and spirit to wholeness. The most direct and widely practised Life discipline. Range varies with the practitioner's skill.",
  "lf_sub_gro": "Growth Magic — Accelerating, directing, or amplifying natural growth in plants, animals, and ecosystems. Subtle use is invisible; heavy use is unmistakable.",
  "lf_sub_sha": "Shapeshifting — Restructuring a living form into another configuration. Can be temporary or permanent depending on how the ruin is inscribed.",
  "lf_sub_pla": "Plague — Weaponised biological change. Spreading transformation, decay, or infection deliberately across living populations. Heavily regulated in most traditions.",
  "lf_sub_emp": "Empathy Link — Sharing sensory or emotional experience between two living beings. Used for communication, coordination, or — in its coercive form — invasion.",
  "lf_sub_fer": "Fertility — Amplifying the creative potential of living things. Applied to seeds, ecosystems, creative work, or relationships. One of the oldest Life ruins.",
  "lf_sub_bb":  "Beast Bonding — Forming deep mutual bonds with animals, sometimes sharing senses or will. The animal retains its nature; the bond does not override instinct.",
  "lf_sub_blm": "Blood Magic — Using the vital essence carried in blood as a medium for Life ruins. Among the most potent disciplines. Costly to the practitioner in proportion to what it achieves.",
  "lf_sub_ver": "Verdancy — The specific magic of plant life — forests, fungi, root networks, and the slow distributed intelligence of growing things. Operates on long time scales.",
  "lf_sub_bon": "Bone Shaping — Restructuring skeletal and mineral structures within living bodies. Precise, surgical, and requires a detailed knowledge of anatomy to use safely.",
  "lf_sub_sou": "Soul Weaving — Working directly with the animating essence of a being. The deepest Life discipline. Few practitioners attempt it; fewer still do so without consequence.",
  "lf_sub_vd":  "Vitality Drain — Drawing life force from one source to empower another. A transfer, not a destruction. The source is weakened in exact proportion to what is taken.",
  "lf_sub_ges": "Gestation — Accelerating or guiding processes of incubation, development, and becoming. Applied to eggs, seeds, wounds healing, or ideas crystallising into form.",

  /* ══════════════════════════════════════════════════
     LIGHT SUBCATEGORIES
  ══════════════════════════════════════════════════ */
  "lt_sub_pyr": "Pyromancy — Summoning, shaping, and directing fire. The most immediately destructive Light discipline. Experienced practitioners can shape flame with surgical precision.",
  "lt_sub_sol": "Solar Calling — Drawing on the power of stars, particularly the sun. Long-range, vast scale. Useless underground or in deep shadow; overwhelming in open daylight.",
  "lt_sub_ill": "Illumination — Producing and directing light to reveal, expose, or guide. Used in healing, navigation, interrogation, and the purging of things that cannot survive scrutiny.",
  "lt_sub_shb": "Shadow Binding — Using the absence of light as a tangible force. Shadows become solid, containable, and weaponisable in the hands of a skilled practitioner.",
  "lt_sub_sta": "Starweaving — Working with the light of distant stars — slow, ancient, cosmic-scale influence. Effects take time to manifest, but are extraordinarily persistent.",
  "lt_sub_bli": "Blindsight — Navigating and perceiving without visible light, using infrared, ultraviolet, or other wavelengths invisible to the unaided eye.",
  "lt_sub_lw":  "Light Weaving — Bending and sculpting light into shapes, barriers, illusions, or encoded messages. The artistic discipline of the Light school.",
  "lt_sub_pri": "Prismatic — Splitting, refracting, and manipulating the colour spectrum. Each wavelength carries different properties that can be separated and applied independently.",
  "lt_sub_glo": "Gloom Craft — Working in deep shadow and low light — not darkness magic, but the liminal space between illumination and absence. Subtle and difficult to detect.",
  "lt_sub_ref": "Reflection — Using mirrors, surfaces, and echoes of light to redirect, amplify, spy, or communicate over great distances.",
  "lt_sub_daw": "Dawn Magic — The specific energy of beginnings, first light, and unrealised potential. Particularly effective for renewal, purification, and breaking stagnation.",
  "lt_sub_dus": "Dusk Magic — The specific energy of endings, last light, and transition. Used in rites of completion, release, and preparing for what comes after.",
  "lt_sub_chr": "Chromamancy — Each colour of the spectrum carries meaning and force. This discipline uses colour itself as the active medium, with each hue producing distinct effects.",
  "lt_sub_al":  "Anti-Light — The creation and manipulation of true darkness — not shadow, but the active, physical absence of light. Rare and deeply unsettling to witness.",
  "lt_sub_lan": "Lantern Rite — Ritual use of contained, sustained flame as a focus for intention and protection. Among the oldest practised forms of Light magic.",

  /* ══════════════════════════════════════════════════
     MEMORY SUBCATEGORIES
  ══════════════════════════════════════════════════ */
  "me_sub_dw":  "Dreamwalking — Entering and navigating the dream-space of a sleeping mind. The dreamer may or may not be aware of the visitor's presence.",
  "me_sub_mr":  "Mind Reading — Accessing the surface or depths of another's conscious or unconscious memory. Depth of access depends on resistance and the practitioner's skill.",
  "me_sub_me":  "Memory Erasure — Selectively removing specific recollections. Precise work — crude use leaves noticeable gaps that the subject may eventually detect.",
  "me_sub_ps":  "Past Sight — Witnessing events that occurred in a specific place or object's history. The ruin reads impressions left in matter by significant occurrences.",
  "me_sub_pe":  "Phantom Echo — Experiencing or replaying a memory so vividly it becomes perceptually real again. Used in testimony, diagnosis, and certain forms of torture.",
  "me_sub_nw":  "Nostalgia Weave — Deliberately invoking emotional memory to influence present feeling or behaviour. Potent and ethically complicated in equal measure.",
  "me_sub_at":  "Archive Touch — Reading the memory stored in objects through physical contact. Every thing that has witnessed significant events retains an impression of them.",
  "me_sub_tw":  "Thought Weaving — Restructuring the patterns of thought themselves — not just memories but the fundamental way a mind processes and connects information.",
  "me_sub_mp":  "Memory Palace — Constructing or inhabiting a precise internal mental architecture for storing and navigating vast quantities of knowledge without loss.",
  "me_sub_gr":  "Grief Ritual — Structured engagement with loss through Memory ruins. Used to process, honour, and eventually release the weight of what is gone.",
  "me_sub_ac":  "Ancestral Call — Accessing the memories and accumulated wisdom of those who came before through blood, object, or place. Lineage as a navigable library.",
  "me_sub_im":  "Identity Mask — Rewriting or obscuring the memories that constitute a self. The most ethically fraught Memory discipline. Leaves no physical evidence.",
  "me_sub_sb":  "Sorrow Binding — Containing, redirecting, or weaponising grief. Sorrow treated as a force with direction and velocity rather than simply a feeling to endure.",
  "me_sub_el":  "Elegy Cast — Preserving the memory of something or someone in permanent form. A ruin that refuses forgetting and binds recollection to a physical anchor.",
  "me_sub_fo":  "Forgetting — The deliberate, sometimes merciful, release of memory. Not erasure — more like opening a hand. What goes is gone, but nothing is forcibly taken.",

  /* ══════════════════════════════════════════════════
     SOUND SUBCATEGORIES
  ══════════════════════════════════════════════════ */
  "so_sub_son": "Sonar — Using sound waves to map, detect, and perceive what cannot be seen. Effective through walls, water, darkness, and other obstacles to light.",
  "so_sub_sir": "Siren Song — Sound used as compulsion. Specific frequencies bypass rational thought and speak directly to instinct, drawing targets toward or away from the source.",
  "so_sub_ec":  "Echo Location — Navigation and spatial awareness through listening to reflected sound. Practitioners develop an intuitive three-dimensional map of their environment.",
  "so_sub_vs":  "Voice Shaping — Modifying the qualities of a voice — pitch, timbre, resonance, authority, and identity. Used for disguise, persuasion, and command.",
  "so_sub_tc":  "Thunder Call — Summoning and directing explosive, concussive sound as a physical force. The pressure wave is the weapon, not the noise.",
  "so_sub_sw":  "Silence Ward — Creating zones where no sound can enter or leave. Used for secure communication, acoustic isolation, and preventing alarm.",
  "so_sub_rs":  "Resonance Strike — Finding the precise frequency at which a target naturally vibrates, then amplifying it until the structure fails. Invisible and exact.",
  "so_sub_wh":  "Whisper Craft — Sound carried impossibly far, or delivered only to a single ear in a crowd with no others hearing. Distance and precision are the twin skills.",
  "so_sub_ca":  "Cacophony — Deliberate sonic chaos — overwhelming, disorienting, destabilising. Used offensively or as cover for other activity happening beneath the noise.",
  "so_sub_sh":  "Seismic Hum — Low-frequency vibration transmitted through ground and stone rather than air. Felt in the body before it is heard. Range is enormous.",
  "so_sub_lu":  "Lullaby — Sound precisely tuned to induce specific states — sleep, calm, emotional openness, or deep vulnerability. Works on animals as well as people.",
  "so_sub_bc":  "Battle Cry — Sound that amplifies courage, coordination, and aggression in those who hear it and choose to receive it. A form of acoustic leadership.",
  "so_sub_hh":  "Harmonic Healing — Specific frequencies that resonate with biological tissue at the cellular level and promote structural repair. Slow but leaves no scar.",
  "so_sub_snw": "Sonic Wall — Standing barriers of controlled, sustained sound that block movement, communication, or the passage of other sound-based ruins.",
  "so_sub_mw":  "Mind Whisper — Sound delivered directly into the mind rather than through the ear. No external vibration is produced. Only the recipient hears anything.",

  /* ══════════════════════════════════════════════════
     SPACE SUBCATEGORIES
  ══════════════════════════════════════════════════ */
  "sp_sub_tel": "Teleportation — Instantaneous relocation of matter from one point to another. Requires either prior knowledge of the destination or a fixed anchor at both ends.",
  "sp_sub_pr":  "Pocket Realm — Creating a contained, stable space that exists outside normal geometry. A room, vault, or sanctuary inscribed inside a ruin.",
  "sp_sub_gs":  "Gravity Shift — Altering the direction and strength of gravitational pull in a defined local area. Disorienting, dangerous, and architecturally destructive at scale.",
  "sp_sub_st":  "Spatial Tear — Opening a rift in the fabric of space. Unstable without continuous maintenance. Useful as a shortcut or weapon; dangerous if abandoned.",
  "sp_sub_pw":  "Phase Walk — Moving through solid matter by briefly existing in the space between spatial layers. Duration is limited; extended use is harmful to the practitioner.",
  "sp_sub_com": "Compression — Reducing the effective distance between two points without physically moving either of them. Everything in between is unaffected.",
  "sp_sub_exp": "Expansion — Increasing effective distance within a defined area. A small room becomes a vast space. Used for storage, isolation, and sanctuary.",
  "sp_sub_vs":  "Void Stepping — Moving through the empty space between things rather than through matter. Faster than walking, leaves no trace, but requires precise spatial awareness.",
  "sp_sub_ap":  "Anchor Point — Fixing a location in space so it cannot be moved, entered unsanctioned, or affected by other Space ruins. A foundation for larger spatial workings.",
  "sp_sub_bw":  "Boundary Ward — Defining and enforcing spatial limits. A territory that cannot be crossed without explicit permission from the one who inscribed the ruin.",
  "sp_sub_dl":  "Dimensional Lock — Preventing any spatial magic from functioning within a defined area. Used as a countermeasure against teleportation and phase walking.",
  "sp_sub_map": "Mapping — Perfect, continuously updated awareness of spatial relationships across a large defined area. The practitioner knows where everything is in real time.",
  "sp_sub_lab": "Labyrinth — Deliberately complicating spatial geometry so that navigation becomes impossible without the key. The path exists; it simply cannot be found by normal means.",
  "sp_sub_wow": "Weight of Worlds — Manipulating mass and gravitational significance at large scale. Used to alter orbits, collapse structures, or anchor floating things to the earth.",
  "sp_sub_fp":  "Folded Path — Bending the geometry of space so that a long journey becomes short without the discontinuity of teleportation. The traveller walks the whole way.",

  /* ══════════════════════════════════════════════════
     TIME SUBCATEGORIES
  ══════════════════════════════════════════════════ */
  "ti_sub_ts":  "Time Stop — Freezing the flow of time in a local area while the practitioner continues to act freely. Duration is limited. Nothing inside the freeze experiences its passage.",
  "ti_sub_cs":  "Chronoshifting — Moving forward or backward through time. The most ambitious and dangerous Time discipline. Paradox risk increases with distance travelled.",
  "ti_sub_ag":  "Aging — Accelerating the natural passage of time through a specific target. Applied to objects, wounds, buildings, or living things. Irreversible once complete.",
  "ti_sub_rej": "Rejuvenation — Reversing aging in a targeted way. Not immortality — more like resetting a clock. The underlying causes of age are not addressed, only its symptoms.",
  "ti_sub_te":  "Temporal Echo — A visible replay of recent events readable to the practitioner. The echo does not interact with the present and cannot be altered.",
  "ti_sub_for": "Foresight — Perceiving probable futures rather than fixed ones. Not prophecy — more like navigating a probability map where some paths are wider than others.",
  "ti_sub_hin": "Hindsight — Perfect recall and re-experience of past events from any perspective that was physically present at the time. Used in investigation and testimony.",
  "ti_sub_par": "Paradox — Deliberately introducing a causal contradiction into the timeline. Extremely dangerous. Used as a weapon of absolute last resort. Consequences are permanent.",
  "ti_sub_eon": "Eon Sight — Perceiving across vast spans of time — geological, civilisational, cosmic scale. The practitioner witnesses eras rather than moments.",
  "ti_sub_dm":  "Decay Mastery — Controlling the rate at which things deteriorate, rust, rot, and break down. Used for preservation, accelerated demolition, and composting at scale.",
  "ti_sub_lw":  "Loop Weave — Creating a repeating time cycle within a defined area. Everything inside repeats on a fixed interval. Escaping requires a ruin of equal or greater power.",
  "ti_sub_ml":  "Momentlock — Freezing a single instant permanently and preserving it outside the normal flow of time. The moment becomes accessible but cannot be changed.",
  "ti_sub_acc": "Acceleration — Speeding up the experienced passage of time for a target or within an area. An hour outside may be a day within. Used for training and rapid growth.",
  "ti_sub_dec": "Deceleration — Slowing the experienced passage of time. Not stopping — stretching. A second becomes a minute. Used for precision work and emergency response.",
  "ti_sub_er":  "Eternal Return — The most philosophical Time discipline. Ensuring that what ends will begin again — applied to cycles, seasons, people, or civilisations.",

  /* ══════════════════════════════════════════════════
     KNOWLEDGE MAIN GLYPHS
  ══════════════════════════════════════════════════ */
  "kn_01": "Arcane Script — A general-purpose inscription glyph for encoding information in a form only the intended reader can decipher.",
  "kn_02": "Bound Tome — Seals knowledge within a container so it cannot be accessed without the correct countersigil.",
  "kn_03": "Cipher Lock — Encrypts a message or location behind a puzzle that only specific knowledge can solve.",
  "kn_04": "Crescent Eye — A perception ruin that grants awareness of things happening just out of direct sight.",
  "kn_05": "Deep Glyph — Buries meaning beneath the surface of an inscription so it reads differently at different levels of understanding.",
  "kn_06": "Elder Mark — Identifies a ruin or practitioner as belonging to a lineage of knowledge stretching back through generations.",
  "kn_07": "Forbidden Seal — Marks and contains knowledge that is too dangerous to access without preparation. Acts as both lock and warning.",
  "kn_08": "Grand Lexicon — A comprehensive index ruin that maps all related inscriptions in a working, making their relationships visible.",
  "kn_09": "Hidden Word — Conceals a message within another message. Only the intended recipient perceives the secondary meaning.",
  "kn_10": "Index Rune — Creates a catalogue of everything inscribed within a defined space or collection.",
  "kn_11": "Judgment Sigil — Weighs truth against falsehood at the moment of inscription. Cannot be added to a false statement without breaking.",
  "kn_12": "Key of Knowing — Unlocks sealed knowledge. Requires the correct intent as well as the physical ruin to function.",
  "kn_13": "Lore Spiral — Preserves accumulated wisdom in an ever-expanding record that organises itself as new knowledge is added.",
  "kn_14": "Mind's Eye — Amplifies perceptive ability, allowing the practitioner to notice details that would otherwise escape attention.",
  "kn_15": "Null Cipher — Cancels an existing encryption without revealing what was hidden — useful for erasing without leaving a trace.",
  "kn_16": "Omen Glyph — Marks a location or object with a warning that future observers with knowledge perception will be able to read.",
  "kn_17": "Pillar of Truth — A foundational inscription that anchors an entire working to verified fact, preventing distortion.",
  "kn_18": "Query Mark — Inscribed as a question. The ruin remains active until answered, drawing relevant knowledge toward the inscriber.",
  "kn_19": "Relic Script — Used to inscribe knowledge into ancient or sacred objects so the information becomes part of the object's identity.",
  "kn_20": "Scholar's Brand — Marks the practitioner as learned. Opens doors, grants credibility, and identifies the bearer to others in the tradition.",
  "kn_21": "Tome Ward — Protects inscribed knowledge from being read, copied, or destroyed by unauthorised parties.",
  "kn_22": "Unseen Verse — A line of inscription that is physically invisible but remains fully active and readable to those who know how to look.",

  /* ══════════════════════════════════════════════════
     LIFE MAIN GLYPHS
  ══════════════════════════════════════════════════ */
  "lf_01": "Bloom Mark — Encourages growth and flowering in whatever it is inscribed upon or near.",
  "lf_02": "Blood Sigil — Uses the practitioner's blood as the medium. What is written in blood carries the writer's life force.",
  "lf_03": "Breath Rune — Sustains breathing in places where air is thin, absent, or toxic.",
  "lf_04": "Cycle Glyph — Marks the natural rhythm of a living system — seasons, heartbeats, migrations, tides.",
  "lf_05": "Deep Root — Anchors something living to a place, making it extremely difficult to uproot or relocate.",
  "lf_06": "Ember Seed — A dormant Life ruin that activates when environmental conditions are correct. Patience written in stone.",
  "lf_07": "Fern Spiral — Represents the unfolding of potential from a tightly coiled beginning. Used in growth and development workings.",
  "lf_08": "Growth Brand — Permanently accelerates natural growth processes in whatever it marks.",
  "lf_09": "Heartbeat Seal — Synchronises biological rhythms between two or more living things.",
  "lf_10": "Ikara Mark — A protective ruin of unclear ancient origin. Shields the bearer's life force from external manipulation.",
  "lf_11": "Joining Knot — Binds two life forces together so that what affects one is felt by the other.",
  "lf_12": "Kin Brand — Marks biological or chosen family connection. Allows life-force sharing across the bonded group.",
  "lf_13": "Living Coil — Represents life in continuous self-renewing motion. Used to sustain long-term biological processes.",
  "lf_14": "Mending Sigil — Accelerates the body's natural healing processes. Not instant — faster.",
  "lf_15": "Nest Rune — Creates a protected space optimised for gestation, incubation, and early development.",
  "lf_16": "Origin Glyph — Marks the point of beginning. Used in birth rites, planting ceremonies, and founding inscriptions.",
  "lf_17": "Pulse Mark — Amplifies the vital signal of a living thing, making it more detectable to Life-sensitive practitioners.",
  "lf_18": "Quicken Seal — Significantly accelerates biological processes within a defined area for a limited time.",
  "lf_19": "Renewal Brand — Resets a living system to a prior healthy state, reversing recent damage or illness.",
  "lf_20": "Sap Glyph — Draws on the internal resources of a living system to power another working. Uses the body as a battery.",
  "lf_21": "Thorn Ring — A defensive perimeter ruin that discourages approach using the principle of natural deterrence.",
  "lf_22": "Vitae Knot — Ties together multiple Life ruins into a cohesive working that functions as a single system.",

  /* ══════════════════════════════════════════════════
     LIGHT MAIN GLYPHS
  ══════════════════════════════════════════════════ */
  "lt_01": "Aurora Mark — Creates a sustained luminous display that signals, distracts, or marks a location across great distance.",
  "lt_02": "Beacon Sigil — Projects a directional beam of light that guides specific targets toward the source.",
  "lt_03": "Brilliance Rune — Amplifies existing light to blinding intensity in a defined area.",
  "lt_04": "Corona Glyph — Surrounds a target with a sustained halo of light that both protects and marks them as significant.",
  "lt_05": "Dawn Brand — Inscribed to mark new beginnings. Releases a pulse of purifying light at a predetermined moment.",
  "lt_06": "Eclipse Seal — Blocks light from a defined area completely, creating a zone of total darkness.",
  "lt_07": "Flare Mark — Produces a sudden, intense burst of light on activation. Single-use. Effective as a signal or distraction.",
  "lt_08": "Gilded Eye — Grants the practitioner's gaze the ability to see through objects, darkness, or illusions.",
  "lt_09": "Halo Rune — Creates a persistent aura of gentle light around a person or object that cannot be extinguished by mundane means.",
  "lt_10": "Ignition Sigil — Sets a target alight. The fire burns at the intensity and duration specified at inscription.",
  "lt_11": "Judgment Ray — Projects a beam that reveals hidden things — invisible objects, concealed ruins, disguised identities.",
  "lt_12": "Kindle Mark — Sustains a small, controlled flame indefinitely without fuel.",
  "lt_13": "Lumen Brand — Permanently marks a surface with stored light that can be released on command.",
  "lt_14": "Midnight Ward — Bends light around a defined area so it appears as natural darkness regardless of surrounding conditions.",
  "lt_15": "Nimbus Glyph — Creates an expanding ring of light that pushes shadow and concealment outward from its centre.",
  "lt_16": "Optic Seal — Locks the visual record of a moment in light so it can be replayed for those who know how to read it.",
  "lt_17": "Photon Ring — A contained loop of light that orbits a point, creating a visible marker and a mild energy barrier.",
  "lt_18": "Quasar Mark — Channels energy from a distant stellar source. Slow to activate but enormously powerful once established.",
  "lt_19": "Radiant Cross — A foundational Light inscription used to anchor larger solar workings.",
  "lt_20": "Solar Brand — Stores the energy of direct sunlight for later release. Charges slowly; discharges instantly.",
  "lt_21": "Twilight Sigil — Works specifically in the transition between light and dark. Effective at dawn and dusk; inert at midday or midnight.",
  "lt_22": "Zenith Rune — Draws maximum power at the moment the sun reaches its highest point. Timing is everything.",

  /* ══════════════════════════════════════════════════
     MEMORY MAIN GLYPHS
  ══════════════════════════════════════════════════ */
  "me_01": "Amber Lock — Preserves a memory in perfect stasis, preventing it from fading, distorting, or being altered over time.",
  "me_02": "Bond Glyph — Links two memories together so that recalling one always surfaces the other.",
  "me_03": "Chronicle Seal — Creates an automatic ongoing record of everything that occurs in a defined space.",
  "me_04": "Dream Brand — Marks the boundary between waking and dreaming, used as an anchor for dreamwalking.",
  "me_05": "Echo Rune — Creates a persistent replay of a specific memory that others in proximity can perceive.",
  "me_06": "Fade Mark — Causes a memory to gradually dissolve over time without the subject noticing the loss.",
  "me_07": "Ghost Imprint — The memory of a person or event left so strongly in a place that it becomes perceivable without ruins.",
  "me_08": "Hollow Sigil — Marks the location of an erased memory — the shape of what was removed, without the content.",
  "me_09": "Impression Glyph — Reads and records the emotional tone of a space or object without capturing specific content.",
  "me_10": "Journal Knot — A personal memory storage ruin that organises recollections chronologically and makes them searchable.",
  "me_11": "Keep Seal — Protects a specific memory from access, alteration, or erasure by external workings.",
  "me_12": "Lost Thread — Marks a memory that has been partially lost, allowing a practitioner to attempt recovery.",
  "me_13": "Mirror Brand — Reflects a memory back to its originator, allowing them to experience it from an outside perspective.",
  "me_14": "Nostalgia Mark — Attaches a powerful emotional pull to a specific memory, making it resurface in moments of stress.",
  "me_15": "Omen Trace — A memory ruin that activates in the future when a specified event occurs, releasing stored information.",
  "me_16": "Past Sigil — Opens a window into the recent history of a specific location, visible to the inscriber.",
  "me_17": "Quill Brand — The practitioner's mark on their own inscriptions — a memory signature that identifies their work.",
  "me_18": "Remnant Glyph — Gathers the faint traces of erased or forgotten memories and consolidates them into partial recovery.",
  "me_19": "Soul Print — Records the complete memory profile of an individual at a specific moment in time.",
  "me_20": "Trace Mark — Follows the path of a memory as it moves through minds, tracking where information has travelled.",
  "me_21": "Vestige Rune — Preserves something that no longer exists — a building, a person, a feeling — in accessible memory form.",
  "me_22": "Witness Seal — Binds a memory to a specific testimony, preventing it from being altered after the fact.",

  /* ══════════════════════════════════════════════════
     SOUND MAIN GLYPHS
  ══════════════════════════════════════════════════ */
  "so_01": "Bell Glyph — Produces a clear, carrying tone at a specified time or trigger. Used for signalling across distance.",
  "so_02": "Call Rune — Sends a targeted sound to a specific person regardless of distance, bypassing all physical barriers.",
  "so_03": "Chord Brand — Creates a sustained harmonic that aligns the emotional states of those within hearing range.",
  "so_04": "Discord Seal — Generates interference frequencies that disrupt other sound-based ruins in the area.",
  "so_05": "Echo Mark — Creates a persistent acoustic reflection at a specific point, replaying the last sounds heard there.",
  "so_06": "Frequency Glyph — Tunes a space or object to resonate at a precisely specified frequency.",
  "so_07": "Groan Sigil — Produces a low, unnerving sound that triggers unease and discourages approach without obvious cause.",
  "so_08": "Harmonic Brand — Permanently aligns an object or space to a specific resonant frequency for use in larger workings.",
  "so_09": "Infra Rune — Generates subsonic frequencies felt as physical pressure rather than heard. Effective through walls.",
  "so_10": "Jangle Mark — Creates a discordant alarm sound when a specified threshold is crossed.",
  "so_11": "Keen Howl — A focused directional sound weapon that disorients and incapacitates at close range.",
  "so_12": "Low Drone — A sustained, barely audible frequency that gradually influences the emotional state of those in range.",
  "so_13": "Mute Glyph — Silences a specific sound source completely without affecting surrounding sounds.",
  "so_14": "Note Seal — Preserves a specific sound in crystallised form for later release.",
  "so_15": "Overtone Brand — Amplifies the harmonic overtones of any sound produced in a space, adding richness and carrying power.",
  "so_16": "Pulse Rune — Creates rhythmic sound emissions at a specified interval. Used for timing, coordination, and navigation.",
  "so_17": "Quake Mark — Generates seismic vibration through ground contact rather than through air.",
  "so_18": "Resonance Sigil — Identifies and marks the natural resonant frequency of its target for use in subsequent workings.",
  "so_19": "Silence Brand — Creates a permanent zone of total acoustic absorption around the inscribed object.",
  "so_20": "Thunder Glyph — Stores acoustic energy for sudden explosive release. Single-use and extremely loud.",
  "so_21": "Undertone Mark — Adds a subliminal frequency beneath audible sound that primes listeners toward a specified emotional state.",
  "so_22": "Vibration Rune — Converts any form of energy input into sustained mechanical vibration at the inscription point.",

  /* ══════════════════════════════════════════════════
     SPACE MAIN GLYPHS
  ══════════════════════════════════════════════════ */
  "sp_01": "Abyss Glyph — Marks a location as a spatial sink — things within its radius are drawn toward its centre.",
  "sp_02": "Boundary Seal — Defines an absolute spatial limit that cannot be crossed by anything the inscriber specifies.",
  "sp_03": "Corridor Brand — Creates a defined spatial tunnel between two points, establishing a stable traversable path.",
  "sp_04": "Depth Rune — Makes a space functionally deeper than it physically is, adding usable volume below or within.",
  "sp_05": "Expanse Mark — Expands the effective interior dimensions of a defined space while leaving its exterior unchanged.",
  "sp_06": "Fold Sigil — Bends two distant points in space toward each other, reducing effective distance.",
  "sp_07": "Gap Glyph — Creates a spatial discontinuity — a gap in space that objects and forces cannot cross.",
  "sp_08": "Hollow Brand — Carves a contained pocket of space out of solid matter without disturbing the surrounding structure.",
  "sp_09": "Interval Rune — Precisely measures and marks the spatial distance between two defined points.",
  "sp_10": "Junction Mark — Creates a stable meeting point where multiple spatial workings converge.",
  "sp_11": "Knot Seal — Ties two locations together so that what happens at one is mirrored at the other.",
  "sp_12": "Liminal Glyph — Marks a threshold — a point of transition between one spatial state and another.",
  "sp_13": "Meridian Brand — Establishes a spatial reference line used to orient and anchor larger spatial workings.",
  "sp_14": "Nexus Sigil — Creates a central hub from which multiple spatial connections radiate.",
  "sp_15": "Orbit Rune — Causes an object to move in a defined path around a fixed point indefinitely.",
  "sp_16": "Portal Mark — One half of a paired ruin that creates a traversable opening between two locations.",
  "sp_17": "Quadrant Glyph — Divides a space into defined sections with different properties in each.",
  "sp_18": "Rift Brand — Forces open a tear in spatial continuity at the inscription point. Requires active maintenance.",
  "sp_19": "Span Seal — Measures and preserves a specific spatial distance as a reference for future workings.",
  "sp_20": "Threshold Rune — Marks a doorway or passage with spatial conditions that apply to anything that crosses it.",
  "sp_21": "Void Mark — Creates a zone of spatial emptiness — no matter, no force, no signal can exist within it.",
  "sp_22": "Warp Sigil — Distorts the geometry of space around the inscription point, bending straight lines into curves.",

  /* ══════════════════════════════════════════════════
     TIME MAIN GLYPHS
  ══════════════════════════════════════════════════ */
  "ti_01": "Age Brand — Accelerates aging in a target at the rate specified at inscription. Permanent.",
  "ti_02": "Blink Rune — Creates a brief, local pause in time — long enough to act but too short to notice from outside.",
  "ti_03": "Chronicle Glyph — Records everything that occurs at the inscription point, organised by time elapsed.",
  "ti_04": "Decay Mark — Accelerates the natural deterioration of a specific object or material.",
  "ti_05": "Epoch Seal — Marks a moment in time as significant, making it easier to locate and return to in subsequent workings.",
  "ti_06": "Flow Brand — Ensures that time moves at its natural rate within a defined area, countering acceleration or deceleration.",
  "ti_07": "Glacial Sigil — Slows time within a defined area to a fraction of its normal rate. Everything inside experiences this as normal.",
  "ti_08": "Hasten Rune — Doubles the rate at which time passes within a small defined area.",
  "ti_09": "Interval Glyph — Marks a specific duration of time and triggers a specified effect when that interval elapses.",
  "ti_10": "Junction Mark — A temporal anchor point used to connect multiple time-based workings.",
  "ti_11": "Kin of Hours — Links the experienced time of two practitioners so they age and tire at the same rate regardless of circumstance.",
  "ti_12": "Loop Seal — Creates a time loop within a defined area. The contents repeat until the ruin is broken.",
  "ti_13": "Moment Brand — Freezes a single moment in perfect preservation, accessible for review but not for alteration.",
  "ti_14": "Now Glyph — Grounds a working firmly in the present moment, preventing it from being affected by past or future alterations.",
  "ti_15": "Old Tongue — A time ruin inscribed in an archaic form of the Language of Creation. Functions as modern ruins do but with greater permanence.",
  "ti_16": "Pause Rune — Holds all time-based processes within a defined area in suspension without freezing them entirely.",
  "ti_17": "Quicksand Mark — Makes time feel subjectively slower for those within range without objectively changing its rate.",
  "ti_18": "Revert Sigil — Returns a defined area or object to its state at a specified prior moment.",
  "ti_19": "Slow Brand — Reduces the rate of time-dependent processes within a target to a specified fraction of normal.",
  "ti_20": "Tide Glyph — Represents the rhythmic ebb and flow of time. Used in workings that operate in cycles.",
  "ti_21": "Unend Seal — Prevents a specified process or state from reaching its natural conclusion. Indefinite suspension.",
  "ti_22": "Vestiges Rune — Gathers and consolidates the faint temporal echoes left by past events at a specific location.",

  /* ══════════════════════════════════════════════════
     TRANSFORMATION SYMBOLS
  ══════════════════════════════════════════════════ */
  "tr_01": "Arrow Up — Move the selected ruin upward on the board.",
  "tr_02": "Arrow Down — Move the selected ruin downward on the board.",
  "tr_03": "Arrow Left — Move the selected ruin to the left on the board.",
  "tr_04": "Arrow Right — Move the selected ruin to the right on the board.",
  "tr_05": "Rotate CW — Rotate the selected ruin clockwise by one step.",
  "tr_06": "Rotate CCW — Rotate the selected ruin counter-clockwise by one step.",
  "tr_07": "Expand — Increase the size of the selected ruin.",
  "tr_08": "Shrink — Decrease the size of the selected ruin.",
  "tr_09": "Flip Horizontal — Mirror the selected ruin left to right.",
  "tr_10": "Flip Vertical — Mirror the selected ruin top to bottom.",
  "tr_11": "Mirror X — Reflect across the vertical axis.",
  "tr_12": "Mirror Y — Reflect across the horizontal axis.",
  "tr_13": "Scale Up — Increase the selected ruin to a larger size.",
  "tr_14": "Scale Down — Reduce the selected ruin to a smaller size.",
  "tr_15": "Align Center — Move the selected ruin to the centre of the board.",
  "tr_16": "Orbit — Place the selected ruin in a circular path around a central point.",
  "tr_17": "Anchor — Fix the selected ruin in place so it cannot be accidentally moved.",
  "tr_18": "Link — Connect two ruins so they move together as one.",
  "tr_19": "Unlink — Separate previously linked ruins.",
  "tr_20": "Free Move — Remove any positional constraints from the selected ruin.",
  "tr_21": "Bind — Bind the selected ruin to a fixed point on the board.",
  "tr_22": "Duplicate — Create an identical copy of the selected ruin.",
  "tr_23": "Erase — Remove the selected ruin from the board entirely.",
  "tr_24": "Merge — Combine two overlapping ruins into a single composite.",
  "tr_25": "Split — Separate a merged ruin back into its component parts.",
  "tr_26": "Reset — Return the selected ruin to its default size, rotation, and position.",
};
