/**
 * RUINS WRITER — Symbol Registry v2
 * Symbol SVGs live in: assets/symbols/<category>/
 * Subcategory SVGs:    assets/symbols/<category>/subcategories/
 * Transformation SVGs: assets/symbols/transformations/
 */

const SYMBOL_CATEGORIES = {
  knowledge: {
    label: "Knowledge",
    subcategories: [
      { id:"kn_sub_div",label:"Divination",src:"assets/symbols/knowledge/subcategories/divination.svg"},
      { id:"kn_sub_enc",label:"Enchantment",src:"assets/symbols/knowledge/subcategories/enchantment.svg"},
      { id:"kn_sub_ill",label:"Illusion",src:"assets/symbols/knowledge/subcategories/illusion.svg"},
      { id:"kn_sub_pro",label:"Prophecy",src:"assets/symbols/knowledge/subcategories/prophecy.svg"},
      { id:"kn_sub_rr",label:"Rune Reading",src:"assets/symbols/knowledge/subcategories/rune_reading.svg"},
      { id:"kn_sub_tel",label:"Telepathy",src:"assets/symbols/knowledge/subcategories/telepathy.svg"},
      { id:"kn_sub_ts",label:"Truthspeaking",src:"assets/symbols/knowledge/subcategories/truthspeaking.svg"},
      { id:"kn_sub_fl",label:"Forbidden Lore",src:"assets/symbols/knowledge/subcategories/forbidden_lore.svg"},
      { id:"kn_sub_scr",label:"Scribing",src:"assets/symbols/knowledge/subcategories/scribing.svg"},
      { id:"kn_sub_mm",label:"Mind Mapping",src:"assets/symbols/knowledge/subcategories/mind_mapping.svg"},
      { id:"kn_sub_am",label:"Arcane Mastery",src:"assets/symbols/knowledge/subcategories/arcane_mastery.svg"},
      { id:"kn_sub_sc",label:"Sigil Craft",src:"assets/symbols/knowledge/subcategories/sigil_craft.svg"},
      { id:"kn_sub_loc",label:"Language of Creation",src:"assets/symbols/knowledge/subcategories/language_of_creation.svg"},
      { id:"kn_sub_bw",label:"Binding Words",src:"assets/symbols/knowledge/subcategories/binding_words.svg"},
      { id:"kn_sub_rev",label:"Revelation",src:"assets/symbols/knowledge/subcategories/revelation.svg"},
    ],
    symbols: [
      { id:"kn_01",label:"Arcane Script",src:"assets/symbols/knowledge/arcane_script.svg"},
      { id:"kn_02",label:"Bound Tome",src:"assets/symbols/knowledge/bound_tome.svg"},
      { id:"kn_03",label:"Cipher Lock",src:"assets/symbols/knowledge/cipher_lock.svg"},
      { id:"kn_04",label:"Crescent Eye",src:"assets/symbols/knowledge/crescent_eye.svg"},
      { id:"kn_05",label:"Deep Glyph",src:"assets/symbols/knowledge/deep_glyph.svg"},
      { id:"kn_06",label:"Elder Mark",src:"assets/symbols/knowledge/elder_mark.svg"},
      { id:"kn_07",label:"Forbidden Seal",src:"assets/symbols/knowledge/forbidden_seal.svg"},
      { id:"kn_08",label:"Grand Lexicon",src:"assets/symbols/knowledge/grand_lexicon.svg"},
      { id:"kn_09",label:"Hidden Word",src:"assets/symbols/knowledge/hidden_word.svg"},
      { id:"kn_10",label:"Index Rune",src:"assets/symbols/knowledge/index_rune.svg"},
      { id:"kn_11",label:"Judgment Sigil",src:"assets/symbols/knowledge/judgment_sigil.svg"},
      { id:"kn_12",label:"Key of Knowing",src:"assets/symbols/knowledge/key_of_knowing.svg"},
      { id:"kn_13",label:"Lore Spiral",src:"assets/symbols/knowledge/lore_spiral.svg"},
      { id:"kn_14",label:"Mind's Eye",src:"assets/symbols/knowledge/minds_eye.svg"},
      { id:"kn_15",label:"Null Cipher",src:"assets/symbols/knowledge/null_cipher.svg"},
      { id:"kn_16",label:"Omen Glyph",src:"assets/symbols/knowledge/omen_glyph.svg"},
      { id:"kn_17",label:"Pillar of Truth",src:"assets/symbols/knowledge/pillar_of_truth.svg"},
      { id:"kn_18",label:"Query Mark",src:"assets/symbols/knowledge/query_mark.svg"},
      { id:"kn_19",label:"Relic Script",src:"assets/symbols/knowledge/relic_script.svg"},
      { id:"kn_20",label:"Scholar's Brand",src:"assets/symbols/knowledge/scholars_brand.svg"},
      { id:"kn_21",label:"Tome Ward",src:"assets/symbols/knowledge/tome_ward.svg"},
      { id:"kn_22",label:"Unseen Verse",src:"assets/symbols/knowledge/unseen_verse.svg"},
    ],
  },
  life: {
    label: "Life",
    subcategories: [
      { id:"lf_sub_nec",label:"Necromancy",src:"assets/symbols/life/subcategories/necromancy.svg"},
      { id:"lf_sub_rev",label:"Revival",src:"assets/symbols/life/subcategories/revival.svg"},
      { id:"lf_sub_hea",label:"Healing",src:"assets/symbols/life/subcategories/healing.svg"},
      { id:"lf_sub_gro",label:"Growth Magic",src:"assets/symbols/life/subcategories/growth_magic.svg"},
      { id:"lf_sub_sha",label:"Shapeshifting",src:"assets/symbols/life/subcategories/shapeshifting.svg"},
      { id:"lf_sub_pla",label:"Plague",src:"assets/symbols/life/subcategories/plague.svg"},
      { id:"lf_sub_emp",label:"Empathy Link",src:"assets/symbols/life/subcategories/empathy_link.svg"},
      { id:"lf_sub_fer",label:"Fertility",src:"assets/symbols/life/subcategories/fertility.svg"},
      { id:"lf_sub_bb",label:"Beast Bonding",src:"assets/symbols/life/subcategories/beast_bonding.svg"},
      { id:"lf_sub_blm",label:"Blood Magic",src:"assets/symbols/life/subcategories/blood_magic.svg"},
      { id:"lf_sub_ver",label:"Verdancy",src:"assets/symbols/life/subcategories/verdancy.svg"},
      { id:"lf_sub_bon",label:"Bone Shaping",src:"assets/symbols/life/subcategories/bone_shaping.svg"},
      { id:"lf_sub_sou",label:"Soul Weaving",src:"assets/symbols/life/subcategories/soul_weaving.svg"},
      { id:"lf_sub_vd",label:"Vitality Drain",src:"assets/symbols/life/subcategories/vitality_drain.svg"},
      { id:"lf_sub_ges",label:"Gestation",src:"assets/symbols/life/subcategories/gestation.svg"},
    ],
    symbols: [
      { id:"lf_01",label:"Bloom Mark",src:"assets/symbols/life/bloom_mark.svg"},
      { id:"lf_02",label:"Blood Sigil",src:"assets/symbols/life/blood_sigil.svg"},
      { id:"lf_03",label:"Breath Rune",src:"assets/symbols/life/breath_rune.svg"},
      { id:"lf_04",label:"Cycle Glyph",src:"assets/symbols/life/cycle_glyph.svg"},
      { id:"lf_05",label:"Deep Root",src:"assets/symbols/life/deep_root.svg"},
      { id:"lf_06",label:"Ember Seed",src:"assets/symbols/life/ember_seed.svg"},
      { id:"lf_07",label:"Fern Spiral",src:"assets/symbols/life/fern_spiral.svg"},
      { id:"lf_08",label:"Growth Brand",src:"assets/symbols/life/growth_brand.svg"},
      { id:"lf_09",label:"Heartbeat Seal",src:"assets/symbols/life/heartbeat_seal.svg"},
      { id:"lf_10",label:"Ikara Mark",src:"assets/symbols/life/ikara_mark.svg"},
      { id:"lf_11",label:"Joining Knot",src:"assets/symbols/life/joining_knot.svg"},
      { id:"lf_12",label:"Kin Brand",src:"assets/symbols/life/kin_brand.svg"},
      { id:"lf_13",label:"Living Coil",src:"assets/symbols/life/living_coil.svg"},
      { id:"lf_14",label:"Mending Sigil",src:"assets/symbols/life/mending_sigil.svg"},
      { id:"lf_15",label:"Nest Rune",src:"assets/symbols/life/nest_rune.svg"},
      { id:"lf_16",label:"Origin Glyph",src:"assets/symbols/life/origin_glyph.svg"},
      { id:"lf_17",label:"Pulse Mark",src:"assets/symbols/life/pulse_mark.svg"},
      { id:"lf_18",label:"Quicken Seal",src:"assets/symbols/life/quicken_seal.svg"},
      { id:"lf_19",label:"Renewal Brand",src:"assets/symbols/life/renewal_brand.svg"},
      { id:"lf_20",label:"Sap Glyph",src:"assets/symbols/life/sap_glyph.svg"},
      { id:"lf_21",label:"Thorn Ring",src:"assets/symbols/life/thorn_ring.svg"},
      { id:"lf_22",label:"Vitae Knot",src:"assets/symbols/life/vitae_knot.svg"},
    ],
  },
  light: {
    label: "Light",
    subcategories: [
      { id:"lt_sub_pyr",label:"Pyromancy",src:"assets/symbols/light/subcategories/pyromancy.svg"},
      { id:"lt_sub_sol",label:"Solar Calling",src:"assets/symbols/light/subcategories/solar_calling.svg"},
      { id:"lt_sub_ill",label:"Illumination",src:"assets/symbols/light/subcategories/illumination.svg"},
      { id:"lt_sub_shb",label:"Shadow Binding",src:"assets/symbols/light/subcategories/shadow_binding.svg"},
      { id:"lt_sub_sta",label:"Starweaving",src:"assets/symbols/light/subcategories/starweaving.svg"},
      { id:"lt_sub_bli",label:"Blindsight",src:"assets/symbols/light/subcategories/blindsight.svg"},
      { id:"lt_sub_lw",label:"Light Weaving",src:"assets/symbols/light/subcategories/light_weaving.svg"},
      { id:"lt_sub_pri",label:"Prismatic",src:"assets/symbols/light/subcategories/prismatic.svg"},
      { id:"lt_sub_glo",label:"Gloom Craft",src:"assets/symbols/light/subcategories/gloom_craft.svg"},
      { id:"lt_sub_ref",label:"Reflection",src:"assets/symbols/light/subcategories/reflection.svg"},
      { id:"lt_sub_daw",label:"Dawn Magic",src:"assets/symbols/light/subcategories/dawn_magic.svg"},
      { id:"lt_sub_dus",label:"Dusk Magic",src:"assets/symbols/light/subcategories/dusk_magic.svg"},
      { id:"lt_sub_chr",label:"Chromamancy",src:"assets/symbols/light/subcategories/chromamancy.svg"},
      { id:"lt_sub_al",label:"Anti-Light",src:"assets/symbols/light/subcategories/anti_light.svg"},
      { id:"lt_sub_lan",label:"Lantern Rite",src:"assets/symbols/light/subcategories/lantern_rite.svg"},
    ],
    symbols: [
      { id:"lt_01",label:"Aurora Mark",src:"assets/symbols/light/aurora_mark.svg"},
      { id:"lt_02",label:"Beacon Sigil",src:"assets/symbols/light/beacon_sigil.svg"},
      { id:"lt_03",label:"Brilliance Rune",src:"assets/symbols/light/brilliance_rune.svg"},
      { id:"lt_04",label:"Corona Glyph",src:"assets/symbols/light/corona_glyph.svg"},
      { id:"lt_05",label:"Dawn Brand",src:"assets/symbols/light/dawn_brand.svg"},
      { id:"lt_06",label:"Eclipse Seal",src:"assets/symbols/light/eclipse_seal.svg"},
      { id:"lt_07",label:"Flare Mark",src:"assets/symbols/light/flare_mark.svg"},
      { id:"lt_08",label:"Gilded Eye",src:"assets/symbols/light/gilded_eye.svg"},
      { id:"lt_09",label:"Halo Rune",src:"assets/symbols/light/halo_rune.svg"},
      { id:"lt_10",label:"Ignition Sigil",src:"assets/symbols/light/ignition_sigil.svg"},
      { id:"lt_11",label:"Judgment Ray",src:"assets/symbols/light/judgment_ray.svg"},
      { id:"lt_12",label:"Kindle Mark",src:"assets/symbols/light/kindle_mark.svg"},
      { id:"lt_13",label:"Lumen Brand",src:"assets/symbols/light/lumen_brand.svg"},
      { id:"lt_14",label:"Midnight Ward",src:"assets/symbols/light/midnight_ward.svg"},
      { id:"lt_15",label:"Nimbus Glyph",src:"assets/symbols/light/nimbus_glyph.svg"},
      { id:"lt_16",label:"Optic Seal",src:"assets/symbols/light/optic_seal.svg"},
      { id:"lt_17",label:"Photon Ring",src:"assets/symbols/light/photon_ring.svg"},
      { id:"lt_18",label:"Quasar Mark",src:"assets/symbols/light/quasar_mark.svg"},
      { id:"lt_19",label:"Radiant Cross",src:"assets/symbols/light/radiant_cross.svg"},
      { id:"lt_20",label:"Solar Brand",src:"assets/symbols/light/solar_brand.svg"},
      { id:"lt_21",label:"Twilight Sigil",src:"assets/symbols/light/twilight_sigil.svg"},
      { id:"lt_22",label:"Zenith Rune",src:"assets/symbols/light/zenith_rune.svg"},
    ],
  },
  memory: {
    label: "Memory",
    subcategories: [
      { id:"me_sub_dw",label:"Dreamwalking",src:"assets/symbols/memory/subcategories/dreamwalking.svg"},
      { id:"me_sub_mr",label:"Mind Reading",src:"assets/symbols/memory/subcategories/mind_reading.svg"},
      { id:"me_sub_me",label:"Memory Erasure",src:"assets/symbols/memory/subcategories/memory_erasure.svg"},
      { id:"me_sub_ps",label:"Past Sight",src:"assets/symbols/memory/subcategories/past_sight.svg"},
      { id:"me_sub_pe",label:"Phantom Echo",src:"assets/symbols/memory/subcategories/phantom_echo.svg"},
      { id:"me_sub_nw",label:"Nostalgia Weave",src:"assets/symbols/memory/subcategories/nostalgia_weave.svg"},
      { id:"me_sub_at",label:"Archive Touch",src:"assets/symbols/memory/subcategories/archive_touch.svg"},
      { id:"me_sub_tw",label:"Thought Weaving",src:"assets/symbols/memory/subcategories/thought_weaving.svg"},
      { id:"me_sub_mp",label:"Memory Palace",src:"assets/symbols/memory/subcategories/memory_palace.svg"},
      { id:"me_sub_gr",label:"Grief Ritual",src:"assets/symbols/memory/subcategories/grief_ritual.svg"},
      { id:"me_sub_ac",label:"Ancestral Call",src:"assets/symbols/memory/subcategories/ancestral_call.svg"},
      { id:"me_sub_im",label:"Identity Mask",src:"assets/symbols/memory/subcategories/identity_mask.svg"},
      { id:"me_sub_sb",label:"Sorrow Binding",src:"assets/symbols/memory/subcategories/sorrow_binding.svg"},
      { id:"me_sub_el",label:"Elegy Cast",src:"assets/symbols/memory/subcategories/elegy_cast.svg"},
      { id:"me_sub_fo",label:"Forgetting",src:"assets/symbols/memory/subcategories/forgetting.svg"},
    ],
    symbols: [
      { id:"me_01",label:"Amber Lock",src:"assets/symbols/memory/amber_lock.svg"},
      { id:"me_02",label:"Bond Glyph",src:"assets/symbols/memory/bond_glyph.svg"},
      { id:"me_03",label:"Chronicle Seal",src:"assets/symbols/memory/chronicle_seal.svg"},
      { id:"me_04",label:"Dream Brand",src:"assets/symbols/memory/dream_brand.svg"},
      { id:"me_05",label:"Echo Rune",src:"assets/symbols/memory/echo_rune.svg"},
      { id:"me_06",label:"Fade Mark",src:"assets/symbols/memory/fade_mark.svg"},
      { id:"me_07",label:"Ghost Imprint",src:"assets/symbols/memory/ghost_imprint.svg"},
      { id:"me_08",label:"Hollow Sigil",src:"assets/symbols/memory/hollow_sigil.svg"},
      { id:"me_09",label:"Impression Glyph",src:"assets/symbols/memory/impression_glyph.svg"},
      { id:"me_10",label:"Journal Knot",src:"assets/symbols/memory/journal_knot.svg"},
      { id:"me_11",label:"Keep Seal",src:"assets/symbols/memory/keep_seal.svg"},
      { id:"me_12",label:"Lost Thread",src:"assets/symbols/memory/lost_thread.svg"},
      { id:"me_13",label:"Mirror Brand",src:"assets/symbols/memory/mirror_brand.svg"},
      { id:"me_14",label:"Nostalgia Mark",src:"assets/symbols/memory/nostalgia_mark.svg"},
      { id:"me_15",label:"Omen Trace",src:"assets/symbols/memory/omen_trace.svg"},
      { id:"me_16",label:"Past Sigil",src:"assets/symbols/memory/past_sigil.svg"},
      { id:"me_17",label:"Quill Brand",src:"assets/symbols/memory/quill_brand.svg"},
      { id:"me_18",label:"Remnant Glyph",src:"assets/symbols/memory/remnant_glyph.svg"},
      { id:"me_19",label:"Soul Print",src:"assets/symbols/memory/soul_print.svg"},
      { id:"me_20",label:"Trace Mark",src:"assets/symbols/memory/trace_mark.svg"},
      { id:"me_21",label:"Vestige Rune",src:"assets/symbols/memory/vestige_rune.svg"},
      { id:"me_22",label:"Witness Seal",src:"assets/symbols/memory/witness_seal.svg"},
    ],
  },
  sound: {
    label: "Sound",
    subcategories: [
      { id:"so_sub_son",label:"Sonar",src:"assets/symbols/sound/subcategories/sonar.svg"},
      { id:"so_sub_sir",label:"Siren Song",src:"assets/symbols/sound/subcategories/siren_song.svg"},
      { id:"so_sub_ec",label:"Echo Location",src:"assets/symbols/sound/subcategories/echo_location.svg"},
      { id:"so_sub_vs",label:"Voice Shaping",src:"assets/symbols/sound/subcategories/voice_shaping.svg"},
      { id:"so_sub_tc",label:"Thunder Call",src:"assets/symbols/sound/subcategories/thunder_call.svg"},
      { id:"so_sub_sw",label:"Silence Ward",src:"assets/symbols/sound/subcategories/silence_ward.svg"},
      { id:"so_sub_rs",label:"Resonance Strike",src:"assets/symbols/sound/subcategories/resonance_strike.svg"},
      { id:"so_sub_wh",label:"Whisper Craft",src:"assets/symbols/sound/subcategories/whisper_craft.svg"},
      { id:"so_sub_ca",label:"Cacophony",src:"assets/symbols/sound/subcategories/cacophony.svg"},
      { id:"so_sub_sh",label:"Seismic Hum",src:"assets/symbols/sound/subcategories/seismic_hum.svg"},
      { id:"so_sub_lu",label:"Lullaby",src:"assets/symbols/sound/subcategories/lullaby.svg"},
      { id:"so_sub_bc",label:"Battle Cry",src:"assets/symbols/sound/subcategories/battle_cry.svg"},
      { id:"so_sub_hh",label:"Harmonic Healing",src:"assets/symbols/sound/subcategories/harmonic_healing.svg"},
      { id:"so_sub_snw",label:"Sonic Wall",src:"assets/symbols/sound/subcategories/sonic_wall.svg"},
      { id:"so_sub_mw",label:"Mind Whisper",src:"assets/symbols/sound/subcategories/mind_whisper.svg"},
    ],
    symbols: [
      { id:"so_01",label:"Bell Glyph",src:"assets/symbols/sound/bell_glyph.svg"},
      { id:"so_02",label:"Call Rune",src:"assets/symbols/sound/call_rune.svg"},
      { id:"so_03",label:"Chord Brand",src:"assets/symbols/sound/chord_brand.svg"},
      { id:"so_04",label:"Discord Seal",src:"assets/symbols/sound/discord_seal.svg"},
      { id:"so_05",label:"Echo Mark",src:"assets/symbols/sound/echo_mark.svg"},
      { id:"so_06",label:"Frequency Glyph",src:"assets/symbols/sound/frequency_glyph.svg"},
      { id:"so_07",label:"Groan Sigil",src:"assets/symbols/sound/groan_sigil.svg"},
      { id:"so_08",label:"Harmonic Brand",src:"assets/symbols/sound/harmonic_brand.svg"},
      { id:"so_09",label:"Infra Rune",src:"assets/symbols/sound/infra_rune.svg"},
      { id:"so_10",label:"Jangle Mark",src:"assets/symbols/sound/jangle_mark.svg"},
      { id:"so_11",label:"Keen Howl",src:"assets/symbols/sound/keen_howl.svg"},
      { id:"so_12",label:"Low Drone",src:"assets/symbols/sound/low_drone.svg"},
      { id:"so_13",label:"Mute Glyph",src:"assets/symbols/sound/mute_glyph.svg"},
      { id:"so_14",label:"Note Seal",src:"assets/symbols/sound/note_seal.svg"},
      { id:"so_15",label:"Overtone Brand",src:"assets/symbols/sound/overtone_brand.svg"},
      { id:"so_16",label:"Pulse Rune",src:"assets/symbols/sound/pulse_rune.svg"},
      { id:"so_17",label:"Quake Mark",src:"assets/symbols/sound/quake_mark.svg"},
      { id:"so_18",label:"Resonance Sigil",src:"assets/symbols/sound/resonance_sigil.svg"},
      { id:"so_19",label:"Silence Brand",src:"assets/symbols/sound/silence_brand.svg"},
      { id:"so_20",label:"Thunder Glyph",src:"assets/symbols/sound/thunder_glyph.svg"},
      { id:"so_21",label:"Undertone Mark",src:"assets/symbols/sound/undertone_mark.svg"},
      { id:"so_22",label:"Vibration Rune",src:"assets/symbols/sound/vibration_rune.svg"},
    ],
  },
  space: {
    label: "Space",
    subcategories: [
      { id:"sp_sub_tel",label:"Teleportation",src:"assets/symbols/space/subcategories/teleportation.svg"},
      { id:"sp_sub_pr",label:"Pocket Realm",src:"assets/symbols/space/subcategories/pocket_realm.svg"},
      { id:"sp_sub_gs",label:"Gravity Shift",src:"assets/symbols/space/subcategories/gravity_shift.svg"},
      { id:"sp_sub_st",label:"Spatial Tear",src:"assets/symbols/space/subcategories/spatial_tear.svg"},
      { id:"sp_sub_pw",label:"Phase Walk",src:"assets/symbols/space/subcategories/phase_walk.svg"},
      { id:"sp_sub_com",label:"Compression",src:"assets/symbols/space/subcategories/compression.svg"},
      { id:"sp_sub_exp",label:"Expansion",src:"assets/symbols/space/subcategories/expansion.svg"},
      { id:"sp_sub_vs",label:"Void Stepping",src:"assets/symbols/space/subcategories/void_stepping.svg"},
      { id:"sp_sub_ap",label:"Anchor Point",src:"assets/symbols/space/subcategories/anchor_point.svg"},
      { id:"sp_sub_bw",label:"Boundary Ward",src:"assets/symbols/space/subcategories/boundary_ward.svg"},
      { id:"sp_sub_dl",label:"Dimensional Lock",src:"assets/symbols/space/subcategories/dimensional_lock.svg"},
      { id:"sp_sub_map",label:"Mapping",src:"assets/symbols/space/subcategories/mapping.svg"},
      { id:"sp_sub_lab",label:"Labyrinth",src:"assets/symbols/space/subcategories/labyrinth.svg"},
      { id:"sp_sub_wow",label:"Weight of Worlds",src:"assets/symbols/space/subcategories/weight_of_worlds.svg"},
      { id:"sp_sub_fp",label:"Folded Path",src:"assets/symbols/space/subcategories/folded_path.svg"},
    ],
    symbols: [
      { id:"sp_01",label:"Abyss Glyph",src:"assets/symbols/space/abyss_glyph.svg"},
      { id:"sp_02",label:"Boundary Seal",src:"assets/symbols/space/boundary_seal.svg"},
      { id:"sp_03",label:"Corridor Brand",src:"assets/symbols/space/corridor_brand.svg"},
      { id:"sp_04",label:"Depth Rune",src:"assets/symbols/space/depth_rune.svg"},
      { id:"sp_05",label:"Expanse Mark",src:"assets/symbols/space/expanse_mark.svg"},
      { id:"sp_06",label:"Fold Sigil",src:"assets/symbols/space/fold_sigil.svg"},
      { id:"sp_07",label:"Gap Glyph",src:"assets/symbols/space/gap_glyph.svg"},
      { id:"sp_08",label:"Hollow Brand",src:"assets/symbols/space/hollow_brand.svg"},
      { id:"sp_09",label:"Interval Rune",src:"assets/symbols/space/interval_rune.svg"},
      { id:"sp_10",label:"Junction Mark",src:"assets/symbols/space/junction_mark.svg"},
      { id:"sp_11",label:"Knot Seal",src:"assets/symbols/space/knot_seal.svg"},
      { id:"sp_12",label:"Liminal Glyph",src:"assets/symbols/space/liminal_glyph.svg"},
      { id:"sp_13",label:"Meridian Brand",src:"assets/symbols/space/meridian_brand.svg"},
      { id:"sp_14",label:"Nexus Sigil",src:"assets/symbols/space/nexus_sigil.svg"},
      { id:"sp_15",label:"Orbit Rune",src:"assets/symbols/space/orbit_rune.svg"},
      { id:"sp_16",label:"Portal Mark",src:"assets/symbols/space/portal_mark.svg"},
      { id:"sp_17",label:"Quadrant Glyph",src:"assets/symbols/space/quadrant_glyph.svg"},
      { id:"sp_18",label:"Rift Brand",src:"assets/symbols/space/rift_brand.svg"},
      { id:"sp_19",label:"Span Seal",src:"assets/symbols/space/span_seal.svg"},
      { id:"sp_20",label:"Threshold Rune",src:"assets/symbols/space/threshold_rune.svg"},
      { id:"sp_21",label:"Void Mark",src:"assets/symbols/space/void_mark.svg"},
      { id:"sp_22",label:"Warp Sigil",src:"assets/symbols/space/warp_sigil.svg"},
    ],
  },
  time: {
    label: "Time",
    subcategories: [
      { id:"ti_sub_ts",label:"Time Stop",src:"assets/symbols/time/subcategories/time_stop.svg"},
      { id:"ti_sub_cs",label:"Chronoshifting",src:"assets/symbols/time/subcategories/chronoshifting.svg"},
      { id:"ti_sub_ag",label:"Aging",src:"assets/symbols/time/subcategories/aging.svg"},
      { id:"ti_sub_rej",label:"Rejuvenation",src:"assets/symbols/time/subcategories/rejuvenation.svg"},
      { id:"ti_sub_te",label:"Temporal Echo",src:"assets/symbols/time/subcategories/temporal_echo.svg"},
      { id:"ti_sub_for",label:"Foresight",src:"assets/symbols/time/subcategories/foresight.svg"},
      { id:"ti_sub_hin",label:"Hindsight",src:"assets/symbols/time/subcategories/hindsight.svg"},
      { id:"ti_sub_par",label:"Paradox",src:"assets/symbols/time/subcategories/paradox.svg"},
      { id:"ti_sub_eon",label:"Eon Sight",src:"assets/symbols/time/subcategories/eon_sight.svg"},
      { id:"ti_sub_dm",label:"Decay Mastery",src:"assets/symbols/time/subcategories/decay_mastery.svg"},
      { id:"ti_sub_lw",label:"Loop Weave",src:"assets/symbols/time/subcategories/loop_weave.svg"},
      { id:"ti_sub_ml",label:"Momentlock",src:"assets/symbols/time/subcategories/momentlock.svg"},
      { id:"ti_sub_acc",label:"Acceleration",src:"assets/symbols/time/subcategories/acceleration.svg"},
      { id:"ti_sub_dec",label:"Deceleration",src:"assets/symbols/time/subcategories/deceleration.svg"},
      { id:"ti_sub_er",label:"Eternal Return",src:"assets/symbols/time/subcategories/eternal_return.svg"},
    ],
    symbols: [
      { id:"ti_01",label:"Age Brand",src:"assets/symbols/time/age_brand.svg"},
      { id:"ti_02",label:"Blink Rune",src:"assets/symbols/time/blink_rune.svg"},
      { id:"ti_03",label:"Chronicle Glyph",src:"assets/symbols/time/chronicle_glyph.svg"},
      { id:"ti_04",label:"Decay Mark",src:"assets/symbols/time/decay_mark.svg"},
      { id:"ti_05",label:"Epoch Seal",src:"assets/symbols/time/epoch_seal.svg"},
      { id:"ti_06",label:"Flow Brand",src:"assets/symbols/time/flow_brand.svg"},
      { id:"ti_07",label:"Glacial Sigil",src:"assets/symbols/time/glacial_sigil.svg"},
      { id:"ti_08",label:"Hasten Rune",src:"assets/symbols/time/hasten_rune.svg"},
      { id:"ti_09",label:"Interval Glyph",src:"assets/symbols/time/interval_glyph.svg"},
      { id:"ti_10",label:"Junction Mark",src:"assets/symbols/time/junction_mark.svg"},
      { id:"ti_11",label:"Kin of Hours",src:"assets/symbols/time/kin_of_hours.svg"},
      { id:"ti_12",label:"Loop Seal",src:"assets/symbols/time/loop_seal.svg"},
      { id:"ti_13",label:"Moment Brand",src:"assets/symbols/time/moment_brand.svg"},
      { id:"ti_14",label:"Now Glyph",src:"assets/symbols/time/now_glyph.svg"},
      { id:"ti_15",label:"Old Tongue",src:"assets/symbols/time/old_tongue.svg"},
      { id:"ti_16",label:"Pause Rune",src:"assets/symbols/time/pause_rune.svg"},
      { id:"ti_17",label:"Quicksand Mark",src:"assets/symbols/time/quicksand_mark.svg"},
      { id:"ti_18",label:"Revert Sigil",src:"assets/symbols/time/revert_sigil.svg"},
      { id:"ti_19",label:"Slow Brand",src:"assets/symbols/time/slow_brand.svg"},
      { id:"ti_20",label:"Tide Glyph",src:"assets/symbols/time/tide_glyph.svg"},
      { id:"ti_21",label:"Unend Seal",src:"assets/symbols/time/unend_seal.svg"},
      { id:"ti_22",label:"Vestiges Rune",src:"assets/symbols/time/vestiges_rune.svg"},
    ],
  },
  transformations: {
    label: "Transformations",
    subcategories: [],
    symbols: [
      { id:"tr_01",label:"Arrow Up",src:"assets/symbols/transformations/arrow_up.svg"},
      { id:"tr_02",label:"Arrow Down",src:"assets/symbols/transformations/arrow_down.svg"},
      { id:"tr_03",label:"Arrow Left",src:"assets/symbols/transformations/arrow_left.svg"},
      { id:"tr_04",label:"Arrow Right",src:"assets/symbols/transformations/arrow_right.svg"},
      { id:"tr_05",label:"Rotate CW",src:"assets/symbols/transformations/rotate_cw.svg"},
      { id:"tr_06",label:"Rotate CCW",src:"assets/symbols/transformations/rotate_ccw.svg"},
      { id:"tr_07",label:"Expand",src:"assets/symbols/transformations/expand.svg"},
      { id:"tr_08",label:"Shrink",src:"assets/symbols/transformations/shrink.svg"},
      { id:"tr_09",label:"Flip Horizontal",src:"assets/symbols/transformations/flip_horizontal.svg"},
      { id:"tr_10",label:"Flip Vertical",src:"assets/symbols/transformations/flip_vertical.svg"},
      { id:"tr_11",label:"Mirror X",src:"assets/symbols/transformations/mirror_x.svg"},
      { id:"tr_12",label:"Mirror Y",src:"assets/symbols/transformations/mirror_y.svg"},
      { id:"tr_13",label:"Scale Up",src:"assets/symbols/transformations/scale_up.svg"},
      { id:"tr_14",label:"Scale Down",src:"assets/symbols/transformations/scale_down.svg"},
      { id:"tr_15",label:"Align Center",src:"assets/symbols/transformations/align_center.svg"},
      { id:"tr_16",label:"Orbit",src:"assets/symbols/transformations/orbit.svg"},
      { id:"tr_17",label:"Anchor",src:"assets/symbols/transformations/anchor.svg"},
      { id:"tr_18",label:"Link",src:"assets/symbols/transformations/link.svg"},
      { id:"tr_19",label:"Unlink",src:"assets/symbols/transformations/unlink.svg"},
      { id:"tr_20",label:"Free Move",src:"assets/symbols/transformations/free_move.svg"},
      { id:"tr_21",label:"Bind",src:"assets/symbols/transformations/bind.svg"},
      { id:"tr_22",label:"Duplicate",src:"assets/symbols/transformations/duplicate.svg"},
      { id:"tr_23",label:"Erase",src:"assets/symbols/transformations/erase.svg"},
      { id:"tr_24",label:"Merge",src:"assets/symbols/transformations/merge.svg"},
      { id:"tr_25",label:"Split",src:"assets/symbols/transformations/split.svg"},
      { id:"tr_26",label:"Reset",src:"assets/symbols/transformations/reset.svg"},
    ],
  },
};

const TAB_ORDER = ["knowledge","life","light","memory","sound","space","time","transformations"];
